import type { ReviewPackage } from "./review-types";

type LocalText = { zh: string; en: string };
type StoryProfile = NonNullable<ReviewPackage["scenario"]["story_profile"]>;
const l = (zh: string, en: string): LocalText => ({ zh, en });

const profiles: Record<string, StoryProfile> = {
  INFRASTRUCTURE_FAILURE: {
    id: "baltimore-key-bridge",
    shortTitle: l("Baltimore 港", "Port of Baltimore"),
    role: l("美国东部区域物流经理", "Eastern U.S. regional logistics manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("桥梁事故与港口中断", "Bridge failure and port interruption"),
    decisionLens: l("恢复时间不确定时保留选择权", "Preserving options under recovery uncertainty"),
    storyIntro: l("你负责一批从巴尔的摩港发往美国东部的重要货物。船期已经排好：太早改港会多花钱，等得太久又可能错过交付。", "You manage an important shipment through Baltimore. Changing ports too early wastes money; waiting too long could miss delivery."),
    goal: l("尽量按时交货，同时避免在消息不清楚时白白改港。", "Deliver on time without changing ports on weak information."),
    stakes: l("关键客户不能断货。", "A key customer cannot run out of stock."),
    dependency: l("Baltimore 港口通道", "Baltimore port gateway"),
    statuses: [l("尚无港口中断证据", "No port disruption evidence yet"), l("航道中断已确认", "Channel disruption confirmed"), l("出现暂定恢复节点", "Tentative recovery milestones available")],
    updates: [l("今天港口仍正常，没有收到中断通知。", "The port is operating normally today and no disruption notice has arrived."), l("桥梁事故已经切断主航道，清障方案和复航日期都还没确定。", "The bridge accident has blocked the main channel; the clearance plan and reopening date are unknown."), l("官方给出了临时通道和全面恢复的目标日期，但天气和残骸仍可能让计划延期。", "Officials published target dates for limited and full access, but weather and wreckage could still delay them.")],
    unknowns: [l("还不知道是否会发生中断。", "You do not yet know whether a disruption will occur."), l("还不知道港口何时恢复，也不知道备用港能否接住这批货。", "You do not know when the port will reopen or whether another port can take the cargo."), l("还不知道恢复日期能否兑现。", "You do not know whether the target dates will hold.")],
    questions: [l("现在没有中断消息，你会先照原计划走，还是花少量精力准备备用港？", "With no disruption news, do you keep the plan or spend a little effort preparing another port?"), l("主航道已经中断，你会继续等待，还是马上把备用港和卡车衔接查清楚？", "With the channel blocked, do you wait or immediately validate another port and trucking connection?"), l("有了暂定恢复日期，你会撤掉备用方案，还是再保留一段时间？", "With tentative reopening dates, do you release the fallback or keep it a little longer?")],
    noEvidence: l("截止时点前没有可用的官方港口中断信息。", "No official port-disruption information is available by this cutoff."),
    monitorTitle: l("维持港口计划并盯住恢复信号", "Keep the port plan and watch recovery signals"),
    mitigationTitle: l("验证替代港与内陆衔接", "Validate alternate ports and inland connections"),
    monitorActions: [l("保留原船期，每四小时查看一次港口消息，不做改港承诺。", "Keep the sailing and check port updates every four hours without committing to another port."), l("暂不改港，等清障时间表更明确后再决定。", "Wait for a clearer clearance timetable before changing ports."), l("按官方目标日期继续原计划；只有日期再次滑动才启动备用港。", "Continue against the target dates and activate the fallback only if they slip again.")],
    monitorTradeoffs: [l("省下备用成本，但突发中断时反应时间更短。", "Avoids fallback cost but leaves less time if disruption occurs."), l("避免过早改港，但可用的替代泊位可能被别人占走。", "Avoids an early diversion but alternate berths may be taken."), l("成本最低，但恢复计划如果落空会再次被动。", "Costs least but creates renewed exposure if recovery slips.")],
    mitigationActions: [l("先向两个备用港询价并确认卡车路线，但暂不下单。", "Ask two alternate ports for prices and trucking options without booking."), l("立即确认备用港泊位、卡车和最后改港时间，形成可撤销方案。", "Confirm alternate berth, trucking, and the last diversion deadline as a reversible plan."), l("继续保留一个备用港和内陆运力，直到主航道稳定运行。", "Keep one alternate port and inland option until the main channel is stable.")],
    mitigationTradeoffs: [l("花少量准备成本，换取事故发生后的反应时间。", "Spends a little on preparation to buy response time."), l("增加准备成本，但不会在恢复时间未知时完全失去选择。", "Adds preparation cost but preserves options while recovery is unknown."), l("会继续占用备用资源，但能防止恢复日期再次推迟。", "Keeps fallback resources tied up but protects against another delay.")],
  },
  DROUGHT_CAPACITY_RESTRICTION: {
    id: "panama-canal-drought",
    shortTitle: l("巴拿马运河", "Panama Canal"),
    role: l("亚洲至美洲海运网络经理", "Asia–Americas ocean network manager"),
    regionLabel: l("中美洲", "Central America"),
    disruptionLabel: l("干旱与运河运力限制", "Drought and canal capacity restrictions"),
    decisionLens: l("把稀缺通航名额分配给不同客户", "Allocating scarce transit slots across customers"),
    storyIntro: l("你负责亚洲到美洲的海运订舱。几家客户都想按原日期过巴拿马运河，但可用名额可能越来越少。", "You manage Asia-to-Americas bookings. Several customers want their original dates, but Panama Canal slots may shrink."),
    goal: l("把有限名额留给最不能延误的货，同时不提前制造恐慌。", "Protect the most time-sensitive cargo without creating premature disruption."),
    stakes: l("医药和促销货有固定到货窗口。", "Medical and promotion cargo have fixed arrival windows."),
    dependency: l("运河预约名额", "Canal booking slots"),
    statuses: [l("当前预约条件未改变", "Current booking conditions unchanged"), l("预约规则开始收紧", "Booking rules begin tightening"), l("每日名额将显著下降", "Daily slots will materially decline")],
    updates: [l("今天的订舱规则没有变化，现有船期仍可使用。", "Today's booking rules are unchanged and current sailings remain available."), l("运河开始调整预约规则，但每日总名额还没有大幅减少。", "The canal has begun changing booking rules, but daily capacity has not yet fallen sharply."), l("官方宣布名额将逐步降到每天 18 个。", "The authority announced that slots will progressively fall to 18 per day.")],
    unknowns: [l("还不知道后续是否真的会削减名额。", "You do not know whether slots will actually be cut."), l("还不知道规则变化会不会影响你手上的船期。", "You do not know whether the rule change will affect your sailings."), l("还不知道限制会持续多久，以及替代航线的真实成本。", "You do not know how long restrictions will last or the true cost of alternatives.")],
    questions: [l("尚无新增限制时，是否应提前改变客户交付顺序？", "Before any new restriction, should customer delivery order change early?"), l("规则变化但名额未大幅下降时，如何避免过早挤占运力？", "When rules change but slots have not materially fallen, how should premature capacity capture be avoided?"), l("名额将降至每日 18 个时，哪些货物应获得保护、延后或绕行？", "When slots fall to 18 per day, which cargo should be protected, deferred, or rerouted?")],
    noEvidence: l("截止时点前没有改变当前航次的新增预约限制。", "No new booking restriction affecting the current sailing is available by this cutoff."),
    monitorTitle: l("维持客户顺序并监测名额", "Keep customer order and monitor slots"),
    mitigationTitle: l("保护关键名额并重排货物", "Protect critical slots and reallocate cargo"),
    monitorActions: [l("保持原订舱顺序，每天更新名额变化。", "Keep the booking order and review slot changes daily."), l("先不抢占额外名额，只核对哪些客户可以晚到。", "Do not capture extra slots yet; identify which customers can accept delay."), l("继续按原顺序排货，只有实际订不到舱时再调整。", "Keep the original order and adjust only when a booking actually fails.")],
    monitorTradeoffs: [l("不会挤占资源，但如果名额突然下降会准备不足。", "Avoids crowding capacity but may leave little preparation time."), l("成本较低，但关键客户可能在规则进一步收紧时失去位置。", "Costs less but critical customers may lose space if rules tighten."), l("操作简单，却可能让高优先级货物与普通货物一起排队。", "Simple to operate but treats critical and standard cargo alike.")],
    mitigationActions: [l("先列出必须保住的货物和可延期货物，不提前购买名额。", "Rank cargo that must be protected and cargo that can wait, without buying slots."), l("为关键货预留少量可取消名额，并给普通货准备延后方案。", "Reserve a small cancellable pool for critical cargo and prepare delays for standard cargo."), l("把 18 个名额优先分给医药和固定窗口货物，其余延期或改走其他航线。", "Prioritize the 18 slots for medical and fixed-window cargo; delay or reroute the rest.")],
    mitigationTradeoffs: [l("多做一次客户分级，但不会过早花钱。", "Adds customer prioritization work without early spend."), l("会产生预留费用，却能保护最重要的交付。", "Creates reservation cost but protects the most important deliveries."), l("保护关键客户，但普通货会更晚或更贵。", "Protects critical customers but delays or raises cost for standard cargo.")],
  },
  MARITIME_SECURITY_THREAT: {
    id: "red-sea-security",
    shortTitle: l("红海安全", "Red Sea security"),
    role: l("欧亚海运安全与网络经理", "Europe–Asia maritime safety and network manager"),
    regionLabel: l("中东", "Middle East"),
    disruptionLabel: l("海上安全事件与绕行", "Maritime security and rerouting"),
    decisionLens: l("用安全阈值治理停航与绕航", "Governing suspension and rerouting through safety thresholds"),
    storyIntro: l("你负责欧亚航线的船员安全和客户交付。红海是最快路线，绕好望角更安全，但会多走约十天。", "You own crew safety and customer delivery on a Europe-Asia route. The Red Sea is fastest; the Cape route is safer but about ten days longer."),
    goal: l("不拿船员安全冒险，同时避免没有依据就让整条航线绕远。", "Protect crews without rerouting the entire network on weak information."),
    stakes: l("船员安全高于时效和运费。", "Crew safety outranks transit time and freight cost."),
    dependency: l("红海航线与船员安全", "Red Sea route and crew safety"),
    statuses: [l("尚无官方安全升级", "No official security escalation yet"), l("袭击与商业绕航已确认", "Attacks and commercial rerouting confirmed"), l("绕航规模与航程影响明确", "Rerouting scale and voyage impact confirmed")],
    updates: [l("今天没有新的官方安全警报，航线仍按原计划运行。", "There is no new official security alert today and the route remains open."), l("多起袭击得到确认，几家大型船公司已经开始绕航。", "Multiple attacks are confirmed and several major carriers have started rerouting."), l("至少 18 家船公司已绕行南非，航程大约增加十天。", "At least 18 carriers are routing around South Africa, adding about ten days.")],
    unknowns: [l("还不知道威胁是否会升级。", "You do not know whether the threat will escalate."), l("还不知道你的船是否会进入同样的风险区域。", "You do not know whether your vessel will face the same risk."), l("还不知道绕航会持续多久，以及客户愿意承担多少延误。", "You do not know how long rerouting will last or how much delay customers will accept.")],
    questions: [l("尚无官方升级时，是否应改变正常航线？", "Without an official escalation, should the normal route change?"), l("同业开始绕航后，何种安全阈值足以触发公司响应？", "Once peers reroute, what safety threshold should trigger a company response?"), l("绕航增加约十天时，应采用个案判断还是统一网络政策？", "When rerouting adds about ten days, should decisions remain case-by-case or follow a network policy?")],
    noEvidence: l("截止时点前没有可用于改变航线的官方安全声明。", "No official security statement supporting a route change is available by this cutoff."),
    monitorTitle: l("维持航线并执行安全监测", "Keep the route under security watch"),
    mitigationTitle: l("按安全门槛准备好望角绕航", "Prepare a safety-governed Cape reroute"),
    monitorActions: [l("维持原航线，要求安全团队每班次复核警报。", "Keep the route and require a security review before each sailing."), l("暂不统一绕航，逐船检查位置、船员和保险条件。", "Do not impose a network-wide reroute; review vessel, crew, and insurance conditions case by case."), l("继续逐船决定，只有进入高风险区的船才绕航。", "Continue vessel-by-vessel decisions and reroute only ships entering the high-risk area.")],
    monitorTradeoffs: [l("保持最快时效，但威胁突然升级时反应窗口较短。", "Preserves speed but leaves less time if threats escalate."), l("减少全网延误，但不同船只可能得到不一致的保护。", "Limits network delay but may protect vessels inconsistently."), l("节省时间和成本，却让安全规则更难统一执行。", "Saves time and cost but makes safety rules harder to apply consistently.")],
    mitigationActions: [l("先计算绕航时效和燃油影响，不改变当前航线。", "Calculate Cape-route timing and fuel impact without changing the current sailing."), l("达到明确安全门槛的船立即绕好望角，其余船等待复核。", "Reroute vessels that meet a clear safety threshold; hold the rest for review."), l("采用统一安全政策：经过高风险区的船一律绕行，并提前通知客户。", "Adopt one safety rule: every vessel crossing the high-risk zone reroutes and customers are notified early.")],
    mitigationTradeoffs: [l("增加计划工作，但提前知道绕航代价。", "Adds planning work but makes rerouting cost visible."), l("明显增加航程，却把安全决定建立在统一门槛上。", "Adds substantial transit time but bases safety decisions on a consistent threshold."), l("最能保护船员，但会带来约十天延误和更高运费。", "Best protects crews but adds about ten days and higher freight cost.")],
  },
  AIR_TRAFFIC_SYSTEM_OUTAGE: {
    id: "faa-notam-outage",
    shortTitle: l("FAA NOTAM 故障", "FAA NOTAM outage"),
    role: l("美国航空货运控制经理", "U.S. air-cargo control manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("航空信息故障与全国停飞", "Aviation information outage and ground stop"),
    decisionLens: l("全网停飞后的货物恢复排序", "Sequencing cargo recovery after a network-wide stop"),
    storyIntro: l("你在航空货运控制中心安排医药、易腐和普通货物。系统一旦故障，飞机可能突然停飞，恢复后也不可能所有货同时起飞。", "You schedule medical, perishable, and standard cargo. A system outage can stop flights suddenly, and not everything can depart first when service resumes."),
    goal: l("先保护最紧急的货，同时让恢复顺序透明可执行。", "Protect the most urgent cargo with a recovery order people can execute."),
    stakes: l("医药和易腐货物经不起长时间等待。", "Medical and perishable cargo cannot tolerate long waits."),
    dependency: l("航班放行与机场网络", "Flight release and airport network"),
    statuses: [l("尚无系统故障通知", "No system-outage notice yet"), l("系统故障但尚未全国停飞", "System failed without a nationwide stop"), l("全国停飞令生效", "Nationwide ground stop in effect")],
    updates: [l("系统正常，所有航班仍按计划运行。", "The system is normal and flights are operating to plan."), l("NOTAM 系统已经故障，新的飞行通知无法处理，但飞机暂时还能起飞。", "The NOTAM system has failed and cannot process new notices, but flights are still moving for now."), l("全国停飞令已经生效，只有军用和医疗救援航班例外。", "A nationwide ground stop is now in force, except for military and medical evacuation flights.")],
    unknowns: [l("还不知道会不会发生系统故障。", "You do not know whether an outage will occur."), l("还不知道系统何时恢复，也不知道停飞令会不会下达。", "You do not know when the system will recover or whether a ground stop will follow."), l("还不知道恢复后各机场能放行多少航班。", "You do not know how much capacity each airport will have after recovery.")],
    questions: [l("正常运行时，是否应为未知系统故障预留恢复资源？", "During normal operations, should recovery resources be held for an unknown failure?"), l("没有恢复时间但仍可飞行时，应先冻结哪些交接与承诺？", "With no restoration estimate but flights still moving, which handoffs should freeze first?"), l("全国停飞后，应如何跨承运人排序医药、易腐和普通货物？", "After a nationwide stop, how should medical, perishable, and standard cargo be sequenced?")],
    noEvidence: l("截止时点前没有 NOTAM 系统故障通知。", "No NOTAM system-outage notice is available by this cutoff."),
    monitorTitle: l("维持航班计划并等待权威指令", "Maintain the flight plan pending authoritative direction"),
    mitigationTitle: l("建立跨承运人的优先恢复序列", "Build a cross-carrier priority recovery sequence"),
    monitorActions: [l("维持原航班计划，只确认紧急联系人和通知渠道。", "Keep the flight plan and confirm emergency contacts and notification channels."), l("允许现有航班继续，但暂停接受新的紧急时效承诺。", "Let current flights continue but stop making new urgent-delivery promises."), l("等待统一复航通知，再按原订舱顺序安排货物。", "Wait for the common restart notice, then use the original booking order.")],
    monitorTradeoffs: [l("不占用额外资源，但故障发生后才开始排序。", "Uses no extra resources but leaves prioritization until an outage occurs."), l("避免无谓停运，但系统恶化时可能来不及保护货物。", "Avoids unnecessary stops but may leave too little time if conditions worsen."), l("规则简单，却可能让普通货排在医药和易腐货前面。", "Simple to apply but may put standard cargo ahead of medical and perishables.")],
    mitigationActions: [l("提前把货物分成医药、易腐和普通三组，不改变当前航班。", "Pre-classify cargo as medical, perishable, or standard without changing flights."), l("冻结非紧急改签，先核对医药和易腐货的剩余时限。", "Freeze non-urgent rebooking and verify remaining time for medical and perishable cargo."), l("建立跨承运人的恢复队列：医药优先，其次易腐，最后普通货。", "Create a cross-carrier recovery queue: medical first, perishables second, standard cargo last.")],
    mitigationTradeoffs: [l("增加准备工作，但故障后可以立即排序。", "Adds preparation but enables immediate prioritization after an outage."), l("会限制销售承诺，却能减少最紧急货物失控。", "Restricts new promises but protects the most urgent cargo."), l("会让普通货更晚，但恢复过程更公平、更可执行。", "Delays standard cargo but makes recovery fairer and easier to execute.")],
  },
  RAIL_LABOR_DISPUTE: {
    id: "us-rail-labor-risk",
    shortTitle: l("美国铁路劳资风险", "U.S. rail labor risk"),
    role: l("北美内陆联运经理", "North American inland intermodal manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("铁路劳资争议与运力风险", "Rail labor dispute and capacity risk"),
    decisionLens: l("在谈判风险下避免过早抢占公路运力", "Avoiding premature truck-capacity capture during negotiations"),
    storyIntro: l("你负责把铁路货物接到公路和仓库。劳资谈判可能导致停运，但卡车运力很贵，太早预订会白花钱。", "You connect rail freight to trucks and warehouses. Labor talks could stop trains, but booking trucks too early is expensive."),
    goal: l("在不中断客户交付的前提下，只购买真正需要的后备运力。", "Buy only the fallback capacity needed to protect customer deliveries."),
    stakes: l("铁路一停，内陆枢纽会很快积压。", "A rail stoppage would quickly congest inland hubs."),
    dependency: l("铁路连续性与联运枢纽", "Rail continuity and intermodal hubs"),
    statuses: [l("尚未成立紧急委员会", "No emergency board yet"), l("争议进入正式治理程序", "Dispute enters formal governance"), l("建议已出但停运未发生", "Recommendations issued without an observed stoppage")],
    updates: [l("谈判仍在继续，没有正式停运程序。", "Talks continue and no formal stoppage process has begun."), l("政府成立紧急委员会，确认争议可能严重影响州际运输。", "An emergency board has been formed because the dispute could seriously disrupt interstate transport."), l("委员会已经提出解决建议，但铁路仍在运行。", "The board has issued recommendations, but trains are still running.")],
    unknowns: [l("还不知道谈判会不会升级。", "You do not know whether talks will escalate."), l("还不知道是否真的停运，以及停运会持续多久。", "You do not know whether a stoppage will occur or how long it would last."), l("还不知道双方是否会接受建议。", "You do not know whether both sides will accept the recommendations.")],
    questions: [l("没有正式升级时，是否应提前锁定卡车和联运容量？", "Without a formal escalation, should truck and intermodal capacity be locked early?"), l("争议可能中断州际运输时，应购买多少有限的选择权？", "When interstate transport could be interrupted, how much fallback capacity should be secured?"), l("谈判建议公布但没有停运时，应继续对冲还是释放运力？", "When recommendations exist but no stoppage has occurred, should the hedge remain?")],
    noEvidence: l("截止时点前没有足以改变铁路计划的正式争议升级。", "No formal dispute escalation sufficient to change the rail plan is available by this cutoff."),
    monitorTitle: l("维持铁路计划并跟踪谈判", "Maintain the rail plan and track negotiations"),
    mitigationTitle: l("预留有限的联运与公路后备", "Reserve a limited intermodal and trucking fallback"),
    monitorActions: [l("维持铁路计划，每天检查谈判状态，不预订卡车。", "Keep the rail plan, check talks daily, and book no trucks."), l("继续走铁路，只列出最容易积压的枢纽和客户。", "Continue by rail and identify the hubs and customers most exposed to backlog."), l("保留现状，等出现正式停运通知再采购公路运力。", "Keep the plan and buy trucking only after a formal stoppage notice.")],
    monitorTradeoffs: [l("没有闲置费用，但停运时很难临时找到卡车。", "Avoids idle cost but trucks may be scarce during a stoppage."), l("不会推高市场价格，但仍没有真正的后备容量。", "Avoids inflating the market but secures no actual fallback."), l("最省钱，却可能在所有人同时抢卡车时失去选择。", "Costs least but risks losing options when everyone books at once.")],
    mitigationActions: [l("先询问卡车和联运价格，不签长期合同。", "Request truck and intermodal prices without signing a long contract."), l("为最关键线路预留少量可取消卡车，其余继续走铁路。", "Reserve a small cancellable truck pool for critical lanes; keep the rest on rail."), l("继续保留关键后备运力，但给每笔预留设置到期日。", "Keep critical fallback capacity with an expiry date on every reservation.")],
    mitigationTradeoffs: [l("多花询价时间，但知道真实的后备成本。", "Adds sourcing work but reveals the real fallback cost."), l("支付少量预留费，换取停运时的确定性。", "Pays a small reservation fee for certainty during a stoppage."), l("建议若被接受，部分预留费可能浪费。", "Some reservation cost may be wasted if the recommendations settle the dispute.")],
  },
  ROAD_TUNNEL_INFRASTRUCTURE_FAILURE: {
    id: "gotthard-tunnel-closure",
    shortTitle: l("Gotthard 隧道", "Gotthard tunnel"),
    role: l("欧洲阿尔卑斯公路网络经理", "European Alpine road-network manager"),
    regionLabel: l("欧洲", "Europe"),
    disruptionLabel: l("山区隧道关闭与跨境绕行", "Alpine tunnel closure and cross-border detours"),
    decisionLens: l("组合绕行距离、驾驶时限与替代方式", "Combining detour distance, driver hours, and alternate modes"),
    storyIntro: l("你安排卡车穿越阿尔卑斯山。主隧道一旦关闭，绕路会增加里程和司机工时，铁路转运则需要重新排期。", "You route trucks across the Alps. A tunnel closure adds distance and driver hours; rail transfer requires new scheduling."),
    goal: l("找到安全、合法且不会频繁改线的运输办法。", "Choose a safe, legal route without repeatedly changing the plan."),
    stakes: l("司机工时和跨境交付时间都不能失控。", "Driver hours and cross-border delivery times must stay controlled."),
    dependency: l("阿尔卑斯南北走廊", "Alpine north–south corridor"),
    statuses: [l("官方关闭信息尚不可用", "Official closure source not yet available"), l("隧道无限期关闭", "Tunnel closed until further notice"), l("维修继续且开放时间待定", "Repairs continue; reopening time pending")],
    updates: [l("今天没有确认的隧道关闭消息。", "There is no confirmed tunnel closure today."), l("官方确认隧道因顶部损坏无限期关闭，损坏范围仍不清楚。", "Officials confirmed an indefinite closure after ceiling damage; the extent is still unclear."), l("损坏部分已经拆除，目标是在本周末前开放，但确切时间要到明天才公布。", "The damaged section is removed and reopening is targeted by week's end, but the exact time comes tomorrow.")],
    unknowns: [l("还不知道隧道是否会关闭。", "You do not know whether the tunnel will close."), l("还不知道公路何时恢复，也不知道铁路还有多少位置。", "You do not know when the road will reopen or how much rail capacity remains."), l("还不知道明天公布的时间是否会改变。", "You do not know whether tomorrow's timing will change.")],
    questions: [l("关闭尚未得到官方确认时，是否应把车辆转移到其他走廊？", "Before official confirmation, should vehicles move to another corridor?"), l("无限期关闭后，应优先公路绕行还是铁路转运？", "After an indefinite closure, should road detours or rail transfer take priority?"), l("维修接近完成但时间仍待定时，如何控制再次改线的成本？", "When repairs near completion but timing remains pending, how should another route change be controlled?")],
    noEvidence: l("截止时点前，官方隧道关闭来源尚未达到保守可用时间。", "The official tunnel-closure source is not yet conservatively available by this cutoff."),
    monitorTitle: l("维持走廊计划并等待开放确认", "Keep the corridor plan pending reopening confirmation"),
    mitigationTitle: l("验证阿尔卑斯绕行与铁路转运", "Validate Alpine detours and rail transfer"),
    monitorActions: [l("维持原路线，只提醒司机出发前再次检查路况。", "Keep the route and ask drivers to recheck conditions before departure."), l("把车辆停在安全节点，等官方给出恢复时间。", "Hold vehicles at safe points until officials publish a reopening time."), l("再等一天获取确切开放时间，不做第二次改线。", "Wait one more day for the exact reopening time and avoid a second route change.")],
    monitorTradeoffs: [l("避免无谓绕行，但临时关闭会打乱司机工时。", "Avoids unnecessary detours but a sudden closure disrupts driver hours."), l("不会承担绕行成本，但交付会继续等待。", "Avoids detour cost but deliveries keep waiting."), l("减少反复改线，却可能再损失一天。", "Avoids repeated changes but may lose another day.")],
    mitigationActions: [l("提前计算两条公路绕行和一条铁路方案的时间，不发车。", "Calculate two road detours and one rail option without dispatching."), l("把短途车改走合法绕行，长途货转为铁路，并逐票批准。", "Use legal road detours for short trips and rail for long freight, approved shipment by shipment."), l("暂时保留绕行和铁路位置，隧道稳定开放后再释放。", "Keep detour and rail options until the tunnel has reopened reliably.")],
    mitigationTradeoffs: [l("增加计划工作，但能避免临时违反工时限制。", "Adds planning but avoids last-minute driver-hours breaches."), l("成本更高、操作更复杂，但货物可以继续移动。", "Costs more and is more complex, but cargo keeps moving."), l("会多占用一天备用资源，但防止开放时间再次改变。", "Ties up fallback capacity for another day but protects against another timing change.")],
  },
  CANAL_VESSEL_GROUNDING: {
    id: "ever-given-grounding",
    shortTitle: l("苏伊士运河搁浅", "Suez Canal grounding"),
    role: l("亚欧班轮航线经理", "Asia–Europe liner-route manager"),
    regionLabel: l("北非", "North Africa"),
    disruptionLabel: l("船舶搁浅与运河堵塞", "Vessel grounding and canal blockage"),
    decisionLens: l("在运河排队与好望角绕航之间选择时机", "Timing the choice between canal queueing and Cape diversion"),
    storyIntro: l("你负责一条亚洲到欧洲的班轮。苏伊士运河如果堵塞，继续排队可能耽误交付，绕好望角则会增加很长航程和燃油成本。", "You manage an Asia-Europe liner service. Waiting at a blocked Suez Canal risks delay; sailing around the Cape adds a long voyage and fuel cost."),
    goal: l("在排队等待和长距离绕航之间选对时机。", "Choose the right moment between waiting in queue and a long diversion."),
    stakes: l("船上货物有交付窗口，长距离绕航代价很高。", "Cargo has delivery windows and a Cape diversion is expensive."),
    dependency: l("苏伊士运河通行与船舶排队", "Suez transit and vessel queue"),
    statuses: [l("搁浅信息尚不可用于决策", "Grounding source not yet decision-eligible"), l("脱困作业进行中", "Refloating response under way"), l("恢复消息尚不可保守使用", "Recovery announcement not yet conservatively available")],
    updates: [l("今天还没有确认的运河堵塞消息。", "There is no confirmed canal blockage today."), l("大型集装箱船已经搁浅，救援队正在尝试脱困，但没有恢复时间。", "A large container ship is grounded and crews are trying to refloat it, with no recovery time."), l("脱困工作仍在继续，现场希望尽快恢复通航，但你还不能确定何时真正放行。", "Refloating continues and authorities hope to restore traffic quickly, but passage timing remains uncertain.")],
    unknowns: [l("还不知道运河是否会被堵住。", "You do not know whether the canal will be blocked."), l("还不知道脱困要几小时还是几天。", "You do not know whether refloating will take hours or days."), l("还不知道恢复后要多久才能清完积压船队。", "You do not know how long the vessel queue will take to clear after reopening.")],
    questions: [l("官方搁浅信息尚不可用时，是否应改变航线？", "Before the official grounding source is available, should the route change?"), l("脱困时间未知时，应继续排队、转运还是准备绕好望角？", "With refloating timing unknown, should cargo queue, transship, or prepare a Cape diversion?"), l("尚不能使用当天恢复消息时，是否已有足够依据承诺长距离绕航？", "When the same-day recovery announcement cannot be used, is there enough evidence for a long diversion?")],
    noEvidence: l("截止时点前，官方搁浅来源尚未达到保守可用时间。", "The official grounding source is not yet conservatively available by this cutoff."),
    monitorTitle: l("保留运河队列并监测脱困进度", "Retain the canal queue and monitor refloating"),
    mitigationTitle: l("验证转运与好望角绕航", "Validate transshipment and Cape diversion"),
    monitorActions: [l("保持原航线，不提前改变船舶计划。", "Keep the original route and make no early change."), l("继续在运河队列中等待，每六小时复核脱困进展。", "Remain in the canal queue and review refloating progress every six hours."), l("再等待一个评审周期，同时计算恢复后的排队时间。", "Wait one more review cycle and estimate the queue after reopening.")],
    monitorTradeoffs: [l("不增加航程，但如果堵塞确认会失去早期选择。", "Adds no distance but loses early options if blockage is confirmed."), l("避免昂贵绕航，却可能在队列中继续累积延误。", "Avoids an expensive diversion but delay may keep growing in queue."), l("可能赶上恢复通航，也可能错过最后的合理绕航时机。", "May benefit from reopening or miss the last sensible diversion point.")],
    mitigationActions: [l("先测算好望角绕航和附近港口转运，不改变航向。", "Estimate a Cape diversion and nearby transshipment without changing course."), l("确认最后转向点、额外燃油和客户延误，再由负责人决定是否绕航。", "Confirm the last turn point, extra fuel, and customer delay before a manager decides."), l("对最紧急货物准备转运，其余船舶继续等待运河恢复。", "Prepare transshipment for the most urgent cargo while the remaining vessels wait.")],
    mitigationTradeoffs: [l("增加计划成本，但提前看清长距离绕航的代价。", "Adds planning cost but makes the long-diversion trade-off clear."), l("可能增加数天航程和大量燃油，但交付时间更可控。", "May add days and major fuel cost but gives more control over delivery timing."), l("保护紧急货物，却增加港口操作和转运风险。", "Protects urgent cargo but adds port handling and transshipment risk.")],
  },
  EXTREME_WEATHER_ROAD_NETWORK: {
    id: "cyclone-gabrielle-roads",
    shortTitle: l("加布里埃尔气旋", "Cyclone Gabrielle"),
    role: l("新西兰北岛公路运输经理", "New Zealand North Island road-freight manager"),
    regionLabel: l("大洋洲", "Oceania"),
    disruptionLabel: l("极端天气与公路网络中断", "Extreme weather and road-network disruption"),
    decisionLens: l("没有安全重卡路线时执行 no-go", "Enforcing no-go when no safe heavy-vehicle route exists"),
    storyIntro: l("你负责新西兰北岛的卡车配送。气旋正在靠近，客户需要物资，但司机不能被派进洪水、倒木或没有重卡绕行路的区域。", "You manage truck deliveries on New Zealand's North Island. A cyclone is approaching; customers need supplies, but drivers cannot be sent into floods, fallen trees, or routes with no heavy-vehicle detour."),
    goal: l("在保障司机安全的前提下，把真正紧急的物资送到能到达的地方。", "Deliver genuinely urgent supplies wherever safe without risking drivers."),
    stakes: l("任何路线都不能以司机安全换取时效。", "No delivery target overrides driver safety."),
    dependency: l("北岛安全公路通道", "Safe North Island road corridors"),
    statuses: [l("首个气旋公路信息尚不可用", "First cyclone road source not yet available"), l("Coromandel 多条公路关闭", "Multiple Coromandel highways closed"), l("Northland 基本隔离", "Northland largely isolated")],
    updates: [l("今天还没有官方道路关闭消息，但天气正在恶化。", "There is no official road closure yet, but weather is worsening."), l("洪水、倒木和碎片已经封闭多段公路，25A 全线关闭。", "Flooding, fallen trees, and debris have closed several roads, including all of SH25A."), l("Northland 多条道路关闭或塌方，当晚没有可供重卡使用的绕行路线。", "Multiple Northland roads are closed or slipped, with no heavy-truck detour available that night.")],
    unknowns: [l("还不知道哪些道路会先关闭。", "You do not know which roads will close first."), l("还不知道剩余道路能否承受重卡，也不知道天气何时缓和。", "You do not know whether remaining roads can take heavy trucks or when weather will ease."), l("还不知道安全通道何时恢复。", "You do not know when a safe corridor will reopen.")],
    questions: [l("主管机构尚未发布关闭信息时，是否应暂停发车？", "Before agency closure information is available, should dispatch stop?"), l("多条道路被洪水和倒木阻断时，哪些任务仍可安全执行？", "When flooding blocks multiple roads, which movements remain safe?"), l("没有重卡绕行路线时，是否必须坚持绝对 no-go？", "When no heavy-vehicle detour exists, must the no-go remain absolute?")],
    noEvidence: l("截止时点前没有可用的 NZTA 气旋道路关闭信息。", "No NZTA cyclone road-closure information is available by this cutoff."),
    monitorTitle: l("在安全集结点等待权威通行信息", "Hold at safe staging points pending authoritative access"),
    mitigationTitle: l("执行 no-go 并验证安全替代方式", "Enforce no-go and validate safe alternatives"),
    monitorActions: [l("照常准备车辆，但出发前必须重新确认路况。", "Prepare vehicles normally but require a final road check before departure."), l("把车辆留在安全集结点，只执行已确认开放的短途任务。", "Hold trucks at safe staging points and run only short trips on confirmed-open roads."), l("所有重卡停止进入隔离区域，等待白天重新评估。", "Stop all heavy trucks entering the isolated area and reassess in daylight.")],
    monitorTradeoffs: [l("保留配送能力，但天气突然恶化时可能临时取消。", "Preserves delivery capacity but may cause last-minute cancellations."), l("保护司机，但部分客户会延迟收到货。", "Protects drivers but delays some customers."), l("最安全，却会让商业货物全部积压。", "Safest, but all commercial freight will accumulate.")],
    mitigationActions: [l("提前设定停运条件，并把紧急物资与普通货分开。", "Set no-go conditions early and separate emergency supplies from standard freight."), l("关闭受影响路线，改用安全短途接驳和固定集结点。", "Close affected routes and use safe short shuttles and fixed staging points."), l("执行绝对 no-go；紧急物资改用政府确认的其他方式，商业货等待。", "Enforce an absolute no-go; move emergency supplies only through government-confirmed alternatives and hold commercial cargo.")],
    mitigationTradeoffs: [l("可能过早取消部分任务，但团队知道何时必须停。", "May cancel some trips early but gives the team a clear stop rule."), l("需要更多交接，配送更慢，但司机不必冒险。", "Adds handoffs and delay but keeps drivers out of danger."), l("商业损失更大，但没有安全重卡路线时不拿生命赌博。", "Causes greater commercial delay but never gambles with lives when no safe truck route exists.")],
  },
  CONTAINER_PORT_CONGESTION: {
    id: "singapore-port-congestion",
    shortTitle: l("新加坡港拥堵", "Singapore port congestion"),
    role: l("东南亚集装箱网络经理", "Southeast Asia container-network manager"),
    regionLabel: l("东南亚", "Southeast Asia"),
    disruptionLabel: l("集装箱港口拥堵", "Container-port congestion"),
    decisionLens: l("在泊位拥堵中重平码头与客户流量", "Rebalancing terminal and customer flows during berth congestion"),
    storyIntro: l("你负责东南亚的集装箱转运。新加坡连接很多后续航班，一条船晚靠泊，可能让多个客户的箱子同时错过下一程。", "You manage Southeast Asian transshipment. A late berth in Singapore can make containers for many customers miss onward sailings."),
    goal: l("保护最重要的转运连接，同时避免一拥堵就把所有箱子改港。", "Protect critical connections without diverting every container at the first sign of congestion."),
    stakes: l("错过转运班次会把两三天等待放大成更长延误。", "A missed connection can turn a two-day berth wait into a much longer delay."),
    dependency: l("泊位、堆场与转运连接", "Berths, yards, and transshipment connections"),
    statuses: [l("泊位等待来源尚不可用", "Berth-wait source not yet available"), l("平均等待约两至三天", "Average waits reach about two to three days"), l("吞吐增长且运力需求持续", "Throughput and capacity demand remain strong")],
    updates: [l("今天没有确认的泊位拥堵消息。", "There is no confirmed berth congestion today."), l("船舶到港不准时加上箱量增加，平均泊位等待已到两至三天。", "Off-schedule arrivals and higher volume have pushed average berth waits to two or three days."), l("今年前五个月箱量同比增加 7.7%，港口称运力需求仍然强劲。", "Container volume rose 7.7% in the first five months and demand remains strong.")],
    unknowns: [l("还不知道拥堵是否会出现。", "You do not know whether congestion will emerge."), l("还不知道哪些转运班次会先受影响。", "You do not know which onward connections will be affected first."), l("还不知道拥堵会持续多久，以及替代港还能接多少箱。", "You do not know how long congestion will last or how many boxes alternate ports can take.")],
    questions: [l("拥堵尚未得到官方确认时，是否应改变挂靠与箱流？", "Before congestion is confirmed, should calls and container flows change?"), l("泊位等待达到两至三天时，应优先保护哪些转运连接？", "When berth waits reach two to three days, which connections should be protected first?"), l("强劲需求持续时，应临时分流还是建立多港口容量规则？", "When demand persists, should flows be temporarily diverted or governed by a multi-port rule?")],
    noEvidence: l("截止时点前，官方泊位等待来源尚未达到保守可用时间。", "The official berth-wait source is not yet conservatively available by this cutoff."),
    monitorTitle: l("维持码头计划并监测泊位队列", "Keep the terminal plan and monitor berth queues"),
    mitigationTitle: l("重平衡挂靠、箱流与替代港", "Rebalance calls, container flows, and alternate ports"),
    monitorActions: [l("维持现有挂靠，每天检查泊位等待。", "Keep current calls and check berth waits daily."), l("保留原港，只优先追踪即将错过转运的箱子。", "Keep Singapore and closely track only containers at risk of missing connections."), l("继续在新加坡处理全部箱流，按客户紧急程度排队。", "Keep all flows in Singapore and queue containers by customer urgency.")],
    monitorTradeoffs: [l("不增加改港成本，但拥堵确认后调整时间更短。", "Avoids diversion cost but leaves less time once congestion is confirmed."), l("操作变化最小，但部分连接仍可能错过。", "Minimizes operational change but some connections may still be missed."), l("流程简单，却让网络继续依赖一个拥堵港口。", "Keeps operations simple but leaves the network dependent on one congested port.")],
    mitigationActions: [l("先列出可使用的替代港和可改接的后续航班，不移动箱子。", "List usable alternate ports and onward sailings without moving containers."), l("只把高价值、快错过转运的箱子分流到备用码头或港口。", "Divert only high-value containers about to miss connections to alternate terminals or ports."), l("建立多港分配规则，把新增箱量按容量分到新加坡和两个备用港。", "Adopt a multi-port allocation rule across Singapore and two alternate ports.")],
    mitigationTradeoffs: [l("增加计划工作，但不会在没有拥堵时乱改港。", "Adds planning without diverting cargo before congestion exists."), l("保护关键连接，但增加转运和改单成本。", "Protects critical connections but adds handling and documentation cost."), l("网络更有韧性，但长期操作更复杂、需要稳定的备用容量。", "Improves resilience but adds lasting complexity and requires reliable alternate capacity.")],
  },
  FLOOD_DAMAGED_HIGHWAY_NETWORK: {
    id: "rio-grande-floods",
    shortTitle: l("巴西南部洪灾", "Southern Brazil floods"),
    role: l("巴西南部公路与集结网络经理", "Southern Brazil road and consolidation-network manager"),
    regionLabel: l("南美洲", "South America"),
    disruptionLabel: l("洪灾与公路网络破碎", "Flooding and fragmented road network"),
    decisionLens: l("在碎片化路网中保护安全走廊与集结点", "Protecting safe corridors and consolidation points in a fragmented network"),
    storyIntro: l("你负责巴西南部的区域配送。洪水把道路切成许多不相连的片段，应急物资必须先走，普通商业货又不能随意进入危险路段。", "You manage regional distribution in southern Brazil. Floods have fragmented the road network; emergency supplies must move first and commercial freight cannot enter unsafe sections."),
    goal: l("先打通安全走廊，把应急和商业货物分开管理。", "Build safe corridors first and manage emergency and commercial freight separately."),
    stakes: l("错误放行会困住司机，也会堵塞救援路线。", "A bad dispatch can strand drivers and block emergency routes."),
    dependency: l("联邦公路与区域集结点", "Federal highways and regional consolidation points"),
    statuses: [l("首份洪灾公路公告尚不可用", "First flood-highway bulletin not yet available"), l("40 个路段完全关闭", "Forty highway sections fully closed"), l("广泛限制仍在持续", "Extensive highway restrictions continue")],
    updates: [l("今天还没有完整的官方洪灾路况。", "There is no complete official flood-road picture today."), l("六条联邦公路共有 40 个路段完全关闭，另有路段只允许救援车辆通行。", "Forty sections across six federal highways are fully closed, and some sections allow emergency vehicles only."), l("关闭数量有所下降，但仍有 11 个路段全封、23 个路段半封，19 个路段正在抢修。", "Closures have eased, but 11 sections remain fully closed, 23 partly closed, and 19 under repair.")],
    unknowns: [l("还不知道哪些走廊真正安全。", "You do not know which corridors are truly safe."), l("还不知道可通行路段能否承受商业车流。", "You do not know whether open sections can absorb commercial traffic."), l("还不知道修复路段何时稳定开放。", "You do not know when repaired sections will remain reliably open.")],
    questions: [l("官方路况尚不可用时，是否应改变区域配送网络？", "Before official road status is available, should the regional network change?"), l("六条公路有 40 个完全关闭路段时，应如何区分应急与商业货运？", "When six highways have 40 full closures, how should emergency and commercial freight be separated?"), l("网络仍碎片化时，应恢复直达还是继续使用安全集结点？", "When the network remains fragmented, should direct delivery resume or safe consolidation remain?")],
    noEvidence: l("截止时点前没有可用的官方洪灾公路公告。", "No official flood-highway bulletin is available by this cutoff."),
    monitorTitle: l("等待核实通行并维持安全集结", "Await verified access and retain safe consolidation"),
    mitigationTitle: l("建立安全走廊与货运优先级", "Build safe corridors and freight priorities"),
    monitorActions: [l("把车辆留在现有集结点，等完整路况后再发车。", "Keep vehicles at current hubs until a complete road picture is available."), l("商业货物继续等待，只允许救援任务使用已确认道路。", "Hold commercial cargo and allow only emergency missions on confirmed roads."), l("继续从集结点分批发车，不恢复点到点直达。", "Continue staged dispatch from hubs and do not restore direct delivery yet.")],
    monitorTradeoffs: [l("最稳妥，但可能错过仍然可走的局部路线。", "Safest, but may overlook local routes that remain usable."), l("保护救援通道，却让商业积压快速增加。", "Protects emergency access but rapidly grows commercial backlog."), l("减少误入封路的风险，但交接次数和等待时间较多。", "Reduces closure risk but adds handoffs and waiting.")],
    mitigationActions: [l("让本地团队先验证短距离安全走廊，并标记禁行区。", "Have local teams validate short safe corridors and mark no-go areas."), l("建立两类队列：救援物资优先，商业货只走不会占用救援道路的路线。", "Create two queues: emergency supplies first; commercial cargo only on routes that do not block relief traffic."), l("保留区域集结点，同时逐条恢复经过验证的直达线路。", "Keep regional hubs while reopening verified direct routes one by one.")],
    mitigationTradeoffs: [l("需要现场核实和协调，但比盲目停运更灵活。", "Requires local verification and coordination but is more flexible than a blanket stop."), l("调度更复杂，却能同时保护救援和有限商业运输。", "Adds scheduling complexity but protects both relief work and limited commerce."), l("恢复更慢、更谨慎，但不会因一次错误放行重新堵塞网络。", "Restores service more slowly but avoids re-fragmenting the network after a bad dispatch.")],
  },
};

export function attachStoryProfiles(packages: ReviewPackage[]): ReviewPackage[] {
  return packages.map((item) => {
    const profile = profiles[item.scenario.scenario_profile.disruption_type];
    if (!profile) throw new Error(`Missing story profile for ${item.scenario.scenario_profile.disruption_type}`);
    return { ...item, scenario: { ...item.scenario, story_profile: profile } };
  });
}
