import type { ReviewPackage } from "./review-types";

type LocalText = { zh: string; en: string };
type StoryProfile = NonNullable<ReviewPackage["scenario"]["story_profile"]>;
const l = (zh: string, en: string): LocalText => ({ zh, en });

const profiles: Record<string, StoryProfile> = {
  INFRASTRUCTURE_FAILURE: {
    id: "baltimore-key-bridge",
    shortTitle: l("Baltimore 港", "Port of Baltimore"),
    role: l("美国东部区域物流经理", "Eastern U.S. regional logistics manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("桥梁事故与港口中断", "Bridge failure and port interruption"),
    decisionLens: l("恢复时间不确定时保留选择权", "Preserving options under recovery uncertainty"),
    dependency: l("Baltimore 港口通道", "Baltimore port gateway"),
    statuses: [l("尚无港口中断证据", "No port disruption evidence yet"), l("航道中断已确认", "Channel disruption confirmed"), l("出现暂定恢复节点", "Tentative recovery milestones available")],
    questions: [l("没有中断证据时，应维持原计划还是提前占用替代港资源？", "With no disruption evidence, should alternate-port resources be reserved early?"), l("恢复时间未知时，应等待还是验证替代港与内陆衔接？", "With recovery timing unknown, should alternate ports and inland links be validated?"), l("暂定恢复时间出现后，应撤回备选方案还是继续保留选择权？", "Once tentative milestones appear, should the contingency be released or retained?")],
    noEvidence: l("截止时点前没有可用的官方港口中断信息。", "No official port-disruption information is available by this cutoff."),
    monitorTitle: l("维持港口计划并盯住恢复信号", "Keep the port plan and watch recovery signals"),
    mitigationTitle: l("验证替代港与内陆衔接", "Validate alternate ports and inland connections"),
  },
  DROUGHT_CAPACITY_RESTRICTION: {
    id: "panama-canal-drought",
    shortTitle: l("巴拿马运河", "Panama Canal"),
    role: l("亚洲至美洲海运网络经理", "Asia–Americas ocean network manager"),
    regionLabel: l("中美洲", "Central America"),
    disruptionLabel: l("干旱与运河运力限制", "Drought and canal capacity restrictions"),
    decisionLens: l("把稀缺通航名额分配给不同客户", "Allocating scarce transit slots across customers"),
    dependency: l("运河预约名额", "Canal booking slots"),
    statuses: [l("当前预约条件未改变", "Current booking conditions unchanged"), l("预约规则开始收紧", "Booking rules begin tightening"), l("每日名额将显著下降", "Daily slots will materially decline")],
    questions: [l("尚无新增限制时，是否应提前改变客户交付顺序？", "Before any new restriction, should customer delivery order change early?"), l("规则变化但名额未大幅下降时，如何避免过早挤占运力？", "When rules change but slots have not materially fallen, how should premature capacity capture be avoided?"), l("名额将降至每日 18 个时，哪些货物应获得保护、延后或绕行？", "When slots fall to 18 per day, which cargo should be protected, deferred, or rerouted?")],
    noEvidence: l("截止时点前没有改变当前航次的新增预约限制。", "No new booking restriction affecting the current sailing is available by this cutoff."),
    monitorTitle: l("维持客户顺序并监测名额", "Keep customer order and monitor slots"),
    mitigationTitle: l("保护关键名额并重排货物", "Protect critical slots and reallocate cargo"),
  },
  MARITIME_SECURITY_THREAT: {
    id: "red-sea-security",
    shortTitle: l("红海安全", "Red Sea security"),
    role: l("欧亚海运安全与网络经理", "Europe–Asia maritime safety and network manager"),
    regionLabel: l("中东", "Middle East"),
    disruptionLabel: l("海上安全事件与绕行", "Maritime security and rerouting"),
    decisionLens: l("用安全阈值治理停航与绕航", "Governing suspension and rerouting through safety thresholds"),
    dependency: l("红海航线与船员安全", "Red Sea route and crew safety"),
    statuses: [l("尚无官方安全升级", "No official security escalation yet"), l("袭击与商业绕航已确认", "Attacks and commercial rerouting confirmed"), l("绕航规模与航程影响明确", "Rerouting scale and voyage impact confirmed")],
    questions: [l("尚无官方升级时，是否应改变正常航线？", "Without an official escalation, should the normal route change?"), l("同业开始绕航后，何种安全阈值足以触发公司响应？", "Once peers reroute, what safety threshold should trigger a company response?"), l("绕航增加约十天时，应采用个案判断还是统一网络政策？", "When rerouting adds about ten days, should decisions remain case-by-case or follow a network policy?")],
    noEvidence: l("截止时点前没有可用于改变航线的官方安全声明。", "No official security statement supporting a route change is available by this cutoff."),
    monitorTitle: l("维持航线并执行安全监测", "Keep the route under security watch"),
    mitigationTitle: l("按安全门槛准备好望角绕航", "Prepare a safety-governed Cape reroute"),
  },
  AIR_TRAFFIC_SYSTEM_OUTAGE: {
    id: "faa-notam-outage",
    shortTitle: l("FAA NOTAM 故障", "FAA NOTAM outage"),
    role: l("美国航空货运控制经理", "U.S. air-cargo control manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("航空信息故障与全国停飞", "Aviation information outage and ground stop"),
    decisionLens: l("全网停飞后的货物恢复排序", "Sequencing cargo recovery after a network-wide stop"),
    dependency: l("航班放行与机场网络", "Flight release and airport network"),
    statuses: [l("尚无系统故障通知", "No system-outage notice yet"), l("系统故障但尚未全国停飞", "System failed without a nationwide stop"), l("全国停飞令生效", "Nationwide ground stop in effect")],
    questions: [l("正常运行时，是否应为未知系统故障预留恢复资源？", "During normal operations, should recovery resources be held for an unknown failure?"), l("没有恢复时间但仍可飞行时，应先冻结哪些交接与承诺？", "With no restoration estimate but flights still moving, which handoffs should freeze first?"), l("全国停飞后，应如何跨承运人排序医药、易腐和普通货物？", "After a nationwide stop, how should medical, perishable, and standard cargo be sequenced?")],
    noEvidence: l("截止时点前没有 NOTAM 系统故障通知。", "No NOTAM system-outage notice is available by this cutoff."),
    monitorTitle: l("维持航班计划并等待权威指令", "Maintain the flight plan pending authoritative direction"),
    mitigationTitle: l("建立跨承运人的优先恢复序列", "Build a cross-carrier priority recovery sequence"),
  },
  RAIL_LABOR_DISPUTE: {
    id: "us-rail-labor-risk",
    shortTitle: l("美国铁路劳资风险", "U.S. rail labor risk"),
    role: l("北美内陆联运经理", "North American inland intermodal manager"),
    regionLabel: l("北美", "North America"),
    disruptionLabel: l("铁路劳资争议与运力风险", "Rail labor dispute and capacity risk"),
    decisionLens: l("在谈判风险下避免过早抢占公路运力", "Avoiding premature truck-capacity capture during negotiations"),
    dependency: l("铁路连续性与联运枢纽", "Rail continuity and intermodal hubs"),
    statuses: [l("尚未成立紧急委员会", "No emergency board yet"), l("争议进入正式治理程序", "Dispute enters formal governance"), l("建议已出但停运未发生", "Recommendations issued without an observed stoppage")],
    questions: [l("没有正式升级时，是否应提前锁定卡车和联运容量？", "Without a formal escalation, should truck and intermodal capacity be locked early?"), l("争议可能中断州际运输时，应购买多少有限的选择权？", "When interstate transport could be interrupted, how much fallback capacity should be secured?"), l("谈判建议公布但没有停运时，应继续对冲还是释放运力？", "When recommendations exist but no stoppage has occurred, should the hedge remain?")],
    noEvidence: l("截止时点前没有足以改变铁路计划的正式争议升级。", "No formal dispute escalation sufficient to change the rail plan is available by this cutoff."),
    monitorTitle: l("维持铁路计划并跟踪谈判", "Maintain the rail plan and track negotiations"),
    mitigationTitle: l("预留有限的联运与公路后备", "Reserve a limited intermodal and trucking fallback"),
  },
  ROAD_TUNNEL_INFRASTRUCTURE_FAILURE: {
    id: "gotthard-tunnel-closure",
    shortTitle: l("Gotthard 隧道", "Gotthard tunnel"),
    role: l("欧洲阿尔卑斯公路网络经理", "European Alpine road-network manager"),
    regionLabel: l("欧洲", "Europe"),
    disruptionLabel: l("山区隧道关闭与跨境绕行", "Alpine tunnel closure and cross-border detours"),
    decisionLens: l("组合绕行距离、驾驶时限与替代方式", "Combining detour distance, driver hours, and alternate modes"),
    dependency: l("阿尔卑斯南北走廊", "Alpine north–south corridor"),
    statuses: [l("官方关闭信息尚不可用", "Official closure source not yet available"), l("隧道无限期关闭", "Tunnel closed until further notice"), l("维修继续且开放时间待定", "Repairs continue; reopening time pending")],
    questions: [l("关闭尚未得到官方确认时，是否应把车辆转移到其他走廊？", "Before official confirmation, should vehicles move to another corridor?"), l("无限期关闭后，应优先公路绕行还是铁路转运？", "After an indefinite closure, should road detours or rail transfer take priority?"), l("维修接近完成但时间仍待定时，如何控制再次改线的成本？", "When repairs near completion but timing remains pending, how should another route change be controlled?")],
    noEvidence: l("截止时点前，官方隧道关闭来源尚未达到保守可用时间。", "The official tunnel-closure source is not yet conservatively available by this cutoff."),
    monitorTitle: l("维持走廊计划并等待开放确认", "Keep the corridor plan pending reopening confirmation"),
    mitigationTitle: l("验证阿尔卑斯绕行与铁路转运", "Validate Alpine detours and rail transfer"),
  },
  CANAL_VESSEL_GROUNDING: {
    id: "ever-given-grounding",
    shortTitle: l("苏伊士运河搁浅", "Suez Canal grounding"),
    role: l("亚欧班轮航线经理", "Asia–Europe liner-route manager"),
    regionLabel: l("北非", "North Africa"),
    disruptionLabel: l("船舶搁浅与运河堵塞", "Vessel grounding and canal blockage"),
    decisionLens: l("在运河排队与好望角绕航之间选择时机", "Timing the choice between canal queueing and Cape diversion"),
    dependency: l("苏伊士运河通行与船舶排队", "Suez transit and vessel queue"),
    statuses: [l("搁浅信息尚不可用于决策", "Grounding source not yet decision-eligible"), l("脱困作业进行中", "Refloating response under way"), l("恢复消息尚不可保守使用", "Recovery announcement not yet conservatively available")],
    questions: [l("官方搁浅信息尚不可用时，是否应改变航线？", "Before the official grounding source is available, should the route change?"), l("脱困时间未知时，应继续排队、转运还是准备绕好望角？", "With refloating timing unknown, should cargo queue, transship, or prepare a Cape diversion?"), l("尚不能使用当天恢复消息时，是否已有足够依据承诺长距离绕航？", "When the same-day recovery announcement cannot be used, is there enough evidence for a long diversion?")],
    noEvidence: l("截止时点前，官方搁浅来源尚未达到保守可用时间。", "The official grounding source is not yet conservatively available by this cutoff."),
    monitorTitle: l("保留运河队列并监测脱困进度", "Retain the canal queue and monitor refloating"),
    mitigationTitle: l("验证转运与好望角绕航", "Validate transshipment and Cape diversion"),
  },
  EXTREME_WEATHER_ROAD_NETWORK: {
    id: "cyclone-gabrielle-roads",
    shortTitle: l("加布里埃尔气旋", "Cyclone Gabrielle"),
    role: l("新西兰北岛公路运输经理", "New Zealand North Island road-freight manager"),
    regionLabel: l("大洋洲", "Oceania"),
    disruptionLabel: l("极端天气与公路网络中断", "Extreme weather and road-network disruption"),
    decisionLens: l("没有安全重卡路线时执行 no-go", "Enforcing no-go when no safe heavy-vehicle route exists"),
    dependency: l("北岛安全公路通道", "Safe North Island road corridors"),
    statuses: [l("首个气旋公路信息尚不可用", "First cyclone road source not yet available"), l("Coromandel 多条公路关闭", "Multiple Coromandel highways closed"), l("Northland 基本隔离", "Northland largely isolated")],
    questions: [l("主管机构尚未发布关闭信息时，是否应暂停发车？", "Before agency closure information is available, should dispatch stop?"), l("多条道路被洪水和倒木阻断时，哪些任务仍可安全执行？", "When flooding blocks multiple roads, which movements remain safe?"), l("没有重卡绕行路线时，是否必须坚持绝对 no-go？", "When no heavy-vehicle detour exists, must the no-go remain absolute?")],
    noEvidence: l("截止时点前没有可用的 NZTA 气旋道路关闭信息。", "No NZTA cyclone road-closure information is available by this cutoff."),
    monitorTitle: l("在安全集结点等待权威通行信息", "Hold at safe staging points pending authoritative access"),
    mitigationTitle: l("执行 no-go 并验证安全替代方式", "Enforce no-go and validate safe alternatives"),
  },
  CONTAINER_PORT_CONGESTION: {
    id: "singapore-port-congestion",
    shortTitle: l("新加坡港拥堵", "Singapore port congestion"),
    role: l("东南亚集装箱网络经理", "Southeast Asia container-network manager"),
    regionLabel: l("东南亚", "Southeast Asia"),
    disruptionLabel: l("集装箱港口拥堵", "Container-port congestion"),
    decisionLens: l("在泊位拥堵中重平码头与客户流量", "Rebalancing terminal and customer flows during berth congestion"),
    dependency: l("泊位、堆场与转运连接", "Berths, yards, and transshipment connections"),
    statuses: [l("泊位等待来源尚不可用", "Berth-wait source not yet available"), l("平均等待约两至三天", "Average waits reach about two to three days"), l("吞吐增长且运力需求持续", "Throughput and capacity demand remain strong")],
    questions: [l("拥堵尚未得到官方确认时，是否应改变挂靠与箱流？", "Before congestion is confirmed, should calls and container flows change?"), l("泊位等待达到两至三天时，应优先保护哪些转运连接？", "When berth waits reach two to three days, which connections should be protected first?"), l("强劲需求持续时，应临时分流还是建立多港口容量规则？", "When demand persists, should flows be temporarily diverted or governed by a multi-port rule?")],
    noEvidence: l("截止时点前，官方泊位等待来源尚未达到保守可用时间。", "The official berth-wait source is not yet conservatively available by this cutoff."),
    monitorTitle: l("维持码头计划并监测泊位队列", "Keep the terminal plan and monitor berth queues"),
    mitigationTitle: l("重平衡挂靠、箱流与替代港", "Rebalance calls, container flows, and alternate ports"),
  },
  FLOOD_DAMAGED_HIGHWAY_NETWORK: {
    id: "rio-grande-floods",
    shortTitle: l("巴西南部洪灾", "Southern Brazil floods"),
    role: l("巴西南部公路与集结网络经理", "Southern Brazil road and consolidation-network manager"),
    regionLabel: l("南美洲", "South America"),
    disruptionLabel: l("洪灾与公路网络破碎", "Flooding and fragmented road network"),
    decisionLens: l("在碎片化路网中保护安全走廊与集结点", "Protecting safe corridors and consolidation points in a fragmented network"),
    dependency: l("联邦公路与区域集结点", "Federal highways and regional consolidation points"),
    statuses: [l("首份洪灾公路公告尚不可用", "First flood-highway bulletin not yet available"), l("40 个路段完全关闭", "Forty highway sections fully closed"), l("广泛限制仍在持续", "Extensive highway restrictions continue")],
    questions: [l("官方路况尚不可用时，是否应改变区域配送网络？", "Before official road status is available, should the regional network change?"), l("六条公路有 40 个完全关闭路段时，应如何区分应急与商业货运？", "When six highways have 40 full closures, how should emergency and commercial freight be separated?"), l("网络仍碎片化时，应恢复直达还是继续使用安全集结点？", "When the network remains fragmented, should direct delivery resume or safe consolidation remain?")],
    noEvidence: l("截止时点前没有可用的官方洪灾公路公告。", "No official flood-highway bulletin is available by this cutoff."),
    monitorTitle: l("等待核实通行并维持安全集结", "Await verified access and retain safe consolidation"),
    mitigationTitle: l("建立安全走廊与货运优先级", "Build safe corridors and freight priorities"),
  },
};

export function attachStoryProfiles(packages: ReviewPackage[]): ReviewPackage[] {
  return packages.map((item) => {
    const profile = profiles[item.scenario.scenario_profile.disruption_type];
    if (!profile) throw new Error(`Missing story profile for ${item.scenario.scenario_profile.disruption_type}`);
    return { ...item, scenario: { ...item.scenario, story_profile: profile } };
  });
}
