from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class OperationsApiInfrastructureTests(unittest.TestCase):
    def test_api_is_jwt_protected_and_staging_scoped(self):
        template = (ROOT / "infrastructure" / "operations-api-staging.yaml").read_text(encoding="utf-8")
        self.assertIn("AuthorizerType: JWT", template)
        self.assertEqual(template.count("AuthorizationType: JWT"), 6)
        self.assertIn("GET /v1/risks", template)
        self.assertIn("GET /v1/outcomes", template)
        self.assertIn("GET /v1/actions", template)
        self.assertIn("GET /v1/pipeline-health", template)
        self.assertIn("GET /v1/forecasts", template)
        self.assertIn("POST /v1/actions/{action_id}/events", template)
        self.assertIn("glap-operations-api-staging", template)
        self.assertNotIn("AWS::Scheduler::Schedule", template)
        self.assertNotIn("AWS::Lambda::Alias", template)

    def test_reliability_and_least_privilege_controls_exist(self):
        template = (ROOT / "infrastructure" / "operations-api-staging.yaml").read_text(encoding="utf-8")
        self.assertNotIn("ReservedConcurrentExecutions", template)
        self.assertIn("ThrottlingBurstLimit: 20", template)
        self.assertIn("ThrottlingRateLimit: 10", template)
        self.assertIn("DeadLetterConfig", template)
        self.assertIn("OperationsApiFailureAlarm", template)
        self.assertIn("OperationsApiThrottleAlarm", template)
        self.assertIn("OperationsApiAccessLogGroup", template)
        self.assertIn("OperationsApiThrottleMetricFilter", template)
        self.assertIn("MetricName: ServiceUnavailable", template)
        self.assertIn("MetricName: ThrottleResponses", template)
        self.assertIn("FilterPattern: '{ $.status = 429 }'", template)
        self.assertIn("DefaultValue: 0", template)
        self.assertIn("cloudwatch:PutMetricData", template)
        self.assertIn("cloudwatch:namespace: GLAP/OperationsApi", template)
        self.assertIn('Format: \'{"requestId":"$context.requestId","routeKey":"$context.routeKey","status":$context.status}\'', template)
        self.assertNotIn("$context.identity.sourceIp", template)
        self.assertNotIn("$context.authorizer", template)
        self.assertIn("vw_lifecycle_action_current_staging_v1", template)
        self.assertIn("fact_lifecycle_action_audit_staging_v1", template)
        self.assertIn("fact_lifecycle_action_staging_v1", template)
        self.assertIn("fact_lifecycle_alert_staging_v1", template)
        self.assertIn("fact_lifecycle_outcome_staging_v1", template)
        self.assertIn("vw_multimodal_forecast_feature_daily_v1", template)
        self.assertIn("fact_shipment_lifecycle_metrics_staging_v1", template)
        self.assertIn("Action: lakeformation:GetDataAccess", template)
        self.assertNotIn("glue:UpdateTable", template)
        self.assertNotIn("s3:DeleteObject", template)
        self.assertIn("PipelineStatusObjectArn", template)
        self.assertIn("PIPELINE_STATUS_S3_URI", template)
        self.assertIn("Action: s3:GetObject", template)

    def test_deployment_is_manual_plan_first(self):
        script = (ROOT / "ops" / "deploy_operations_api_stack.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$Apply", script)
        self.assertIn("if (-not $Apply)", script)
        self.assertIn("Plan only", script)
        self.assertIn("glap_operations_api.py", script)
        self.assertIn("Public Pages write access: False", script)
        self.assertIn("JWT issuer configured:", script)
        self.assertIn("Allowed origin configured:", script)
        self.assertNotIn('Write-Host "  JWT issuer: $JwtIssuer"', script)
        self.assertNotIn('Write-Host "  Allowed origin: $AllowedOrigin"', script)
        self.assertNotIn("update-alias", script.lower())

        role_verifier = (
            ROOT / "ops" / "verify_operations_roles_staging.ps1"
        ).read_text(encoding="utf-8")
        self.assertIn("Queue read HTTP statuses:", role_verifier)
        self.assertIn("Risk read HTTP statuses:", role_verifier)
        self.assertIn("Outcome read HTTP statuses:", role_verifier)
        self.assertIn("Pipeline Health read HTTP statuses:", role_verifier)
        self.assertIn("Forecast read HTTP statuses:", role_verifier)
        self.assertIn("Pipeline Health summary:", role_verifier)
        self.assertIn("risk cutoff dates valid", role_verifier)
        self.assertIn("risk status filter valid", role_verifier)
        self.assertIn("pending outcomes remain not observed", role_verifier)
        self.assertIn("observed outcome evidence valid", role_verifier)
        self.assertIn("pipeline health six-stage contract valid", role_verifier)
        self.assertIn("pipeline health temporal boundary valid", role_verifier)
        self.assertIn("pipeline health infrastructure identifiers redacted", role_verifier)
        self.assertIn("forecast temporal boundary valid", role_verifier)
        self.assertIn("forecast future simulation isolated", role_verifier)
        self.assertIn("forecast evidence classification valid", role_verifier)
        self.assertIn("forecast entity and infrastructure identifiers redacted", role_verifier)
        self.assertNotIn("Tokens or user identifiers printed: True", role_verifier)

        workflow = (ROOT / ".github" / "workflows" / "deploy-operations-api-staging.yml").read_text(encoding="utf-8")
        self.assertIn("workflow_dispatch:", workflow)
        self.assertIn("push:", workflow)
        self.assertIn("branches:\n      - main", workflow)
        self.assertIn("default: plan", workflow)
        self.assertIn("GLAP_OPERATIONS_JWT_ISSUER", workflow)
        self.assertIn("GLAP_OPERATIONS_JWT_AUDIENCE", workflow)
        self.assertIn("GLAP_OPERATIONS_INTERNAL_ORIGIN", workflow)
        self.assertIn("GLAP_PIPELINE_STATUS_S3_URI", workflow)
        self.assertIn("glap-pipeline-reliability-staging", workflow)
        self.assertIn("AWS_STAGING_ROLE_ARN", workflow)
        self.assertIn("Resolve protected staging configuration privately", workflow)
        self.assertIn("::add-mask::$issuer", workflow)
        self.assertIn('} >> "$GITHUB_ENV"', workflow)
        self.assertIn("Expected exactly one Cognito pool candidate", workflow)
        self.assertIn("Expected exactly one internal HTTPS origin candidate", workflow)
        self.assertIn("glap-operations-identity-staging", workflow)
        self.assertIn("Dedicated identity stack configuration available", workflow)
        discovery = workflow.split(
            "Resolve protected staging configuration privately", 1
        )[1].split("Validate protected staging configuration", 1)[0]
        self.assertNotIn("GITHUB_STEP_SUMMARY", discovery)
        self.assertNotIn("describe-user-pool-client", discovery)
        self.assertLess(
            workflow.index("Configure AWS staging credentials"),
            workflow.index("Resolve protected staging configuration privately"),
        )
        self.assertIn("if: github.event_name == 'workflow_dispatch' && inputs.action == 'deploy'", workflow)
        self.assertIn("Public Pages write access: \\`false\\`", workflow)
        self.assertNotIn("schedule:", workflow)

    def test_governed_view_access_is_exact_and_plan_first(self):
        script = (
            ROOT / "ops" / "configure_operations_api_data_access.ps1"
        ).read_text(encoding="utf-8")
        self.assertIn("[switch]$Apply", script)
        self.assertIn("if (-not $Apply)", script)
        self.assertIn("Plan only", script)
        self.assertIn('"OperationsApiRole"', script)
        self.assertIn('"lakeformation", "list-permissions"', script)
        self.assertIn("lakeformation grant-permissions", script)
        self.assertIn('@("DESCRIBE")', script)
        self.assertIn('@("SELECT", "DESCRIBE")', script)
        self.assertIn("vw_lifecycle_action_current_staging_v1", script)
        self.assertIn("fact_lifecycle_action_audit_staging_v1", script)
        self.assertIn("fact_lifecycle_action_staging_v1", script)
        self.assertIn("Two backing Action tables: SELECT, DESCRIBE", script)
        self.assertIn("Operational Alert table: SELECT, DESCRIBE", script)
        self.assertIn("Operational Outcome table: SELECT, DESCRIBE", script)
        self.assertIn("Operational Forecast source table: SELECT, DESCRIBE", script)
        self.assertIn("IAM_ALLOWED_PRINCIPALS", script)
        self.assertIn("Exact table access enforced by Lambda IAM policy: True", script)
        self.assertIn("Other tables or views: False", script)
        self.assertIn("Write or grantable permissions: False", script)
        self.assertIn("[System.Text.UTF8Encoding]::new($false)", script)
        self.assertNotIn('--permissions ALL', script)
        self.assertNotIn("WITH_GRANT_OPTION", script)
        self.assertNotIn("revoke-permissions", script)

    def test_reliability_verifier_is_non_mutating_plan_first_and_self_cleaning(self):
        script = (
            ROOT / "ops" / "verify_operations_reliability_staging.ps1"
        ).read_text(encoding="utf-8")
        self.assertIn("[switch]$Apply", script)
        self.assertIn("[switch]$InjectFailure", script)
        self.assertIn("RecoveryTimeoutSeconds", script)
        self.assertIn("if (-not $Apply)", script)
        self.assertIn("Apply requires -InjectFailure", script)
        self.assertIn("Existing audit event replay only: True", script)
        self.assertIn("New or changed Action expected: False", script)
        self.assertIn("idempotent_replay", script)
        self.assertIn("Invoke-ConcurrentPosts", script)
        self.assertIn("Where-Object Status -eq 429", script)
        self.assertIn("ThrottlingBurstLimit=1,ThrottlingRateLimit=1", script)
        self.assertIn("Staging API throttle restoration failed", script)
        self.assertIn("Wait-AlarmsObserved", script)
        self.assertIn('Wait-Alarms $alarmNames "OK"', script)
        self.assertIn("Synchronous API DLQ remained empty", script)
        self.assertIn("update-function-configuration", script)
        self.assertIn("Staging Lambda environment restoration failed", script)
        self.assertIn("external actions", script)
        self.assertIn("admin-delete-user", script)
        self.assertIn('"cognito-idp", "list-users"', script)
        self.assertIn("removed and confirmed", script)
        self.assertIn("finally", script)
        self.assertNotIn("DELETE FROM", script.upper())
        self.assertNotIn("MERGE INTO", script.upper())
        self.assertNotIn("INSERT INTO", script.upper())

    def test_discovery_bootstrap_is_read_only_and_plan_first(self):
        script = (
            ROOT / "ops" / "configure_operations_api_discovery.ps1"
        ).read_text(encoding="utf-8")
        self.assertIn("[switch]$Apply", script)
        self.assertIn("if (-not $Apply)", script)
        self.assertIn("Plan only", script)
        self.assertIn("GLAPOperationsIdentityDiscovery", script)
        self.assertIn('"cognito-idp:ListUserPools"', script)
        self.assertIn('"cognito-idp:ListUserPoolClients"', script)
        self.assertIn('"amplify:ListApps"', script)
        self.assertIn('"apigateway:GET"', script)
        self.assertIn('"cloudformation:DescribeStacks"', script)
        self.assertIn('stack/${IdentityStackName}/*', script)
        self.assertIn('stack/${PipelineReliabilityStackName}/*', script)
        self.assertIn('"lambda:GetFunction"', script)
        self.assertIn('function:${ActionMutationFunctionName}', script)
        self.assertIn('"glue:GetTable"', script)
        self.assertIn('table/${SourceDatabase}/vw_lifecycle_action_current_staging_v1', script)
        self.assertIn('table/${SourceDatabase}/${ForecastSourceTable}', script)
        self.assertIn("Deployment permissions: False", script)
        self.assertIn("Self-modifying deployer permission: False", script)
        self.assertNotIn('"iam:PassRole"', script)
        self.assertNotIn('"lambda:InvokeFunction"', script)
        self.assertNotIn('"lambda:Update', script)
        self.assertNotIn('"glue:Update', script)
        self.assertNotIn('"glue:Create', script)
        self.assertNotIn('"cloudformation:Create', script)
        self.assertNotIn('"cloudformation:Execute', script)
        self.assertNotIn('"cloudformation:Delete', script)
        self.assertNotIn('"s3:', script)
        self.assertNotIn('"sqs:', script)
        self.assertNotIn('"apigateway:POST"', script)
        self.assertNotIn('"apigateway:PUT"', script)
        self.assertNotIn('"apigateway:PATCH"', script)
        self.assertNotIn('"apigateway:DELETE"', script)
        self.assertIn("Remove-Item -LiteralPath $policyPath", script)


if __name__ == "__main__":
    unittest.main()
