import type { HeroCase, LocalText, PilotOption } from "./hero-case-types";

const l = (zh: string, en: string): LocalText => ({ zh, en });

const option = (
  id: "A" | "B",
  titleZh: string,
  titleEn: string,
  bodyZh: string,
  bodyEn: string,
  tradeoffZh: string,
  tradeoffEn: string,
): PilotOption => ({
  id,
  title: l(titleZh, titleEn),
  body: l(bodyZh, bodyEn),
  tradeoff: l(tradeoffZh, tradeoffEn),
});

const sameMonitor = (
  titleZh: string,
  titleEn: string,
  bodyZh: string,
  bodyEn: string,
  tradeoffZh: string,
  tradeoffEn: string,
): [PilotOption, PilotOption] => [
  option("A", titleZh, titleEn, bodyZh, bodyEn, tradeoffZh, tradeoffEn),
  option("B", titleZh, titleEn, bodyZh, bodyEn, tradeoffZh, tradeoffEn),
];

export const heroCases: HeroCase[] = [
  {
    id: "baltimore-key-bridge",
    title: l("巴尔的摩港通行中断", "Port of Baltimore access disruption"),
    shortTitle: l("Baltimore 港", "Port of Baltimore"),
    role: l("美国东部区域物流经理", "Eastern U.S. regional logistics manager"),
    mode: "OCEAN",
    disruption: l("桥梁事故与港口通行中断", "Bridge failure and port access disruption"),
    region: l("北美", "North America"),
    decisionLens: l("不确定性下的选择权", "Option value under uncertainty"),
    stages: [
      {
        moment: "T0",
        date: l("2024 年 3 月 26 日 · 00:00 EDT", "26 March 2024 · 00:00 EDT"),
        status: l("暂未收到港口异常通知", "No port disruption notice received"),
        context: l(
          "你负责一批计划经 Baltimore 港进入美国东部的高优先级货物。现在是 3 月 26 日 00:00。到目前为止，你还没有收到港口关闭或航道受阻的通知。这批货对交期敏感，但当前信息还不足以说明原计划已经受到影响。",
          "You manage high-priority cargo planned to enter the eastern United States through the Port of Baltimore. It is 00:00 on 26 March. So far, you have received no notice that the port is closed or the channel is obstructed. The shipment is time-sensitive, but nothing currently shows that the original plan has been affected.",
        ),
        newEvidence: [
          l("截至 00:00，没有收到港口关闭或航道受阻的通知。", "By 00:00, no notice of a port closure or obstructed channel has been received."),
          l("你此刻并不知道几小时后会发生什么。", "At this moment, you do not know what will happen in the hours ahead."),
        ],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("经 Baltimore 港进入美国东部", "Via Baltimore into the eastern U.S.") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 8 天", "About 8 days") },
          { label: l("客户优先级", "Customer priority"), value: l("高；延误可能影响承诺交期", "High; delay may affect delivery commitment"), tone: "warning" },
          { label: l("备选运输", "Backup transport"), value: l("存在其他路径；运力和成本尚未确认", "Other routes exist; capacity and cost unconfirmed"), tone: "positive" },
        ],
        question: l("你现在需要决定：维持原运输计划继续观察，还是改变这批货的安排？", "You must now decide: keep the original transport plan under observation, or change the shipment arrangements?"),
        options: sameMonitor(
          "维持原计划，继续观察", "Keep the original plan under observation",
          "暂不调整路线。继续关注港口和承运商通知；只有出现可靠的中断消息后，才准备备选安排。", "Keep the route unchanged. Continue watching port and carrier notices; prepare an alternative only after reliable disruption information appears.",
          "避免在信息不足时过早行动，但突发恶化时可能延迟响应。", "Avoids acting too early, but may delay response if conditions worsen suddenly.",
        ),
      },
      {
        moment: "T1",
        date: l("2024 年 3 月 31 日 · 00:00 EDT", "31 March 2024 · 00:00 EDT"),
        status: l("港口通行中断已确认", "Port access disruption confirmed"),
        context: l("弗朗西斯·斯科特·基桥坍塌后，Baltimore 港的安全通航受到严重影响。应急清理与水下评估已经开始，但具体清理计划和可靠恢复时间仍不明确。", "After the Francis Scott Key Bridge collapse, safe access to the Port of Baltimore is severely disrupted. Emergency clearance and underwater assessment are under way, but there is no settled removal plan or reliable recovery date."),
        newEvidence: [
          l("应急行动已启动，开始评估恢复安全通航所需的残骸清理。", "Emergency operations have begun assessing debris removal needed to restore safe navigation."),
          l("初步水下分析正在进行，运营性清理计划尚未确定。", "Preliminary underwater analysis is under way; the operational removal plan is not yet determined."),
        ],
        operationalFacts: [
          { label: l("原计划路线", "Original route"), value: l("经 Baltimore 港；已受阻", "Via Baltimore; now disrupted"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 7 天", "About 7 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高；延误可能影响承诺交期", "High; delay may affect delivery commitment"), tone: "warning" },
          { label: l("恢复预期", "Recovery outlook"), value: l("尚无可靠时间", "No reliable timeline") },
          { label: l("备选运输", "Backup transport"), value: l("存在其他路径；运力和成本尚未确认", "Other routes exist; capacity and cost unconfirmed"), tone: "positive" },
        ],
        question: l("你现在需要决定：继续等待恢复时间明确，还是先为高优先级货物准备备选运输方案？", "You must now decide: wait for a clearer recovery timeline, or prepare backup transport for the high-priority cargo?"),
        options: [
          option("A", "现在准备备选运输方案", "Prepare backup transport now", "立即核实替代港口与运力，比较成本、时效和交期影响，为关键货物准备范围受限的改道建议。任何预订或改道仍需要负责人批准。", "Validate alternate ports and capacity, compare cost, lead time and delivery impacts, and prepare a bounded reroute proposal. Any booking or reroute still requires accountable approval.", "更早保护库存和交期，但可行性和增量成本仍待验证。", "Protects inventory and delivery commitments earlier, but feasibility and incremental cost remain unverified."),
          option("B", "维持原计划，等待更多信息", "Keep the original plan and wait", "暂不改道。继续跟踪港口清理进度，在出现更可靠的恢复时间前不改变安排，并每日检查库存和客户交期。", "Do not reroute yet. Continue tracking clearance and keep transport unchanged until a more reliable recovery timeline appears, while reviewing inventory and delivery commitments daily.", "避免过早承担改道成本，但已确认的高风险暴露将继续存在。", "Avoids premature rerouting cost, but leaves confirmed high-risk exposure unmitigated."),
        ],
      },
      {
        moment: "T2",
        date: l("2024 年 4 月 5 日 · 00:00 EDT", "5 April 2024 · 00:00 EDT"),
        status: l("出现暂定恢复时间表", "Tentative recovery timeline available"),
        context: l("清理工作继续推进。当局首次给出暂定恢复节点：4 月底前实现受限单向通行，5 月底前恢复完整航道。这些日期仍受天气和残骸复杂度影响。", "Clearance work continues. Authorities have issued tentative milestones: limited one-way access by the end of April and full channel access by the end of May. Both remain subject to weather and wreckage complexity."),
        newEvidence: [
          l("预计 4 月底前开放受限单向通道。", "Limited one-way access is targeted by the end of April."),
          l("目标为 5 月底前恢复完整航道。", "Full channel access is targeted by the end of May."),
          l("两个时间点仍可能因天气和残骸复杂度变动。", "Both milestones may still move because of weather and wreckage complexity."),
        ],
        operationalFacts: [
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 6 天", "About 6 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高；延误可能影响承诺交期", "High; delay may affect delivery commitment"), tone: "warning" },
          { label: l("预计有限通行", "Expected limited access"), value: l("4 月底前", "By the end of April") },
          { label: l("预计全面恢复", "Expected full access"), value: l("5 月底前；仍可能变动", "By the end of May; still subject to change") },
          { label: l("备选运输", "Backup transport"), value: l("存在其他路径；运力和成本尚未确认", "Other routes exist; capacity and cost unconfirmed"), tone: "positive" },
        ],
        question: l("有了暂定恢复时间后，你应继续准备备选运输，还是暂缓改道并密切跟进？", "With tentative recovery dates now available, should you keep preparing backup transport or hold off on rerouting and monitor closely?"),
        options: [
          option("A", "暂缓改道，密切跟进恢复进度", "Hold off on rerouting and monitor recovery", "暂不改变路由。跟踪航道开放进度并每日检查库存与交期；只在里程碑再次滑动或库存缓冲不足时提交备选建议。", "Keep routes unchanged for now. Track channel milestones and review inventory and delivery commitments daily; submit an alternative only if milestones slip or the buffer becomes insufficient.", "避免在恢复路径出现后承担过高改道成本，但库存缓冲已继续下降。", "Avoids costly rerouting after a recovery path appears, but the inventory buffer continues to fall."),
          option("B", "继续准备备选运输方案", "Keep preparing backup transport", "尽管已有暂定恢复节点，仍立即验证替代港口与运力，为高优先级货物准备范围受限的改道建议。任何执行仍需负责人批准。", "Despite the tentative milestones, validate alternate ports and capacity and prepare a bounded reroute proposal for high-priority cargo. Any execution still requires accountable approval.", "为恢复日期再次延后保留主动权，但可能投入不必要的规划成本。", "Preserves options if recovery slips again, but may spend effort on a contingency that is not needed."),
        ],
      },
    ],
  },
  {
    id: "panama-canal-drought",
    title: l("2023 年干旱期间的巴拿马运河运力限制", "Panama Canal capacity restrictions during the 2023 drought"),
    shortTitle: l("巴拿马运河", "Panama Canal"),
    role: l("亚洲至美洲海运网络经理", "Asia–Americas ocean network manager"),
    mode: "OCEAN",
    disruption: l("干旱与通航能力限制", "Drought and transit-capacity restriction"),
    region: l("中美洲", "Central America"),
    decisionLens: l("稀缺运力的客户分配", "Allocating scarce capacity across customers"),
    stages: [
      {
        moment: "T0",
        date: l("2023 年 10 月 25 日 · 00:00 EST", "25 October 2023 · 00:00 EST"),
        status: l("尚未收到新的预约限制", "No new booking restriction received"),
        context: l("你负责一批计划经巴拿马运河运往美洲的集装箱货物。市场已经在讨论干旱，但截至这个决策时点，你还没有收到会改变当前航次的新预约通知。", "You manage container cargo planned to cross the Panama Canal toward the Americas. The market is discussing drought conditions, but at this decision time you have received no new booking notice that changes the current sailing plan."),
        newEvidence: [l("当前航次的预约条件尚未改变。", "Booking conditions for the current sailing have not changed."), l("没有新的通航削减时间表可供使用。", "No new transit-reduction schedule is available.")],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("经巴拿马运河", "Via the Panama Canal") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 16 天", "About 16 days") },
          { label: l("客户优先级", "Customer priority"), value: l("中等；存在调整时间", "Medium; some planning time remains") },
          { label: l("备选运输", "Backup transport"), value: l("可绕行；舱位、时效和成本尚未确认", "Rerouting is possible; capacity, time and cost unconfirmed"), tone: "positive" },
        ],
        question: l("还没有新增限制，你会照常预约，还是提前调整客户之间的运力分配？", "With no new restriction, would you keep booking normally or change capacity allocation across customers early?"),
        options: sameMonitor("维持正常预约与客户顺序", "Keep normal booking and customer order", "沿用当前预约和客户交付顺序。继续跟踪运河与承运商通知，只在当前航次的通航条件发生变化后重新评估分配规则。", "Keep the current booking and customer-delivery order. Track canal and carrier notices, and reassess allocation rules only if transit conditions change for the sailing.", "避免在没有约束时制造客户优先级冲突，但若名额突然收紧，留给重新分配的时间会更少。", "Avoids creating customer-priority conflict without a constraint, but leaves less time to reallocate if slots tighten suddenly."),
      },
      {
        moment: "T1",
        date: l("2023 年 10 月 26 日 · 00:00 EST", "26 October 2023 · 00:00 EST"),
        status: l("预约条件即将调整", "Booking conditions scheduled to change"),
        context: l("运河管理局延长了一项现有预约条件，并安排 Panamax 船闸预约转入新条件。这会影响计划组织，但尚未出现大幅削减每日通航名额的信息。", "The Canal Authority has extended one booking condition and scheduled Panamax reservations to move to a new condition. Planning is affected, but there is not yet information showing a major cut in daily transit slots."),
        newEvidence: [l("一项预约条件被延长。", "One booking condition has been extended."), l("Panamax 船闸预约将转入新条件。", "Panamax reservations are scheduled to move to a new condition.")],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("继续经巴拿马运河", "Still via the Panama Canal") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 15 天", "About 15 days") },
          { label: l("客户优先级", "Customer priority"), value: l("中等", "Medium") },
          { label: l("当前影响", "Current impact"), value: l("预约程序变化；尚无高强度通航削减", "Booking-process change; no major slot cut yet") },
          { label: l("备选运输", "Backup transport"), value: l("可绕行；详细成本尚未确认", "Rerouting is possible; detailed cost unconfirmed"), tone: "positive" },
        ],
        question: l("预约规则会调整，但通航名额还没有实质减少，你现在会改变客户分配顺序吗？", "Booking rules will change, but transit slots have not materially fallen. Would you change customer allocation order now?"),
        options: sameMonitor("维持现有客户顺序，跟踪名额", "Keep customer order and monitor slots", "不改变已经确认的预约或客户交付顺序。继续跟踪每日通航名额和承运商排期；只有出现实质削减后才重新分配。", "Do not change confirmed bookings or customer-delivery order. Track daily transit slots and carrier schedules and reallocate only after a material reduction.", "最符合已有客户承诺，但如果名额突然收紧，所有客户可能同时进入紧急协调。", "Best preserves existing commitments, but a sudden slot cut could push every customer into urgent coordination at once."),
      },
      {
        moment: "T2",
        date: l("2023 年 10 月 31 日 · 00:00 EST", "31 October 2023 · 00:00 EST"),
        status: l("干旱将显著压缩通航名额", "Drought will materially reduce transit slots"),
        context: l("运河管理局报告 Gatun 湖水位异常偏低，10 月降雨比历史常态低 41%。从 11 月到次年 2 月，预约名额将逐步降至每日 18 个。", "The Canal Authority reports unusually low Gatun Lake levels and October rainfall 41% below normal. Booking slots will progressively fall to 18 per day from November through February."),
        newEvidence: [l("Gatun 湖水位处于该时段异常低位。", "Gatun Lake is at an unusually low level for the season."), l("10 月降雨比历史常态低 41%。", "October rainfall is 41% below the recorded norm."), l("预约名额将逐步降至每日 18 个。", "Booking slots will progressively fall to 18 per day.")],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("经巴拿马运河；名额显著收紧", "Via Panama; slots materially tightening"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 10 天", "About 10 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("运力趋势", "Capacity outlook"), value: l("将持续收紧至次年 2 月", "Tightening through February") },
          { label: l("备选运输", "Backup transport"), value: l("可绕行；会增加航程和成本", "Rerouting is possible; adds distance and cost"), tone: "positive" },
        ],
        question: l("每日名额将降至 18 个，你要按现有客户比例分配，还是优先保护可能停线的货物？", "Daily slots will fall to 18. Should capacity remain proportional across customers or protect cargo facing production stoppage first?"),
        options: [
          option("A", "按现有客户比例分配名额", "Allocate slots proportionally across customers", "继续为各客户按现有货量比例争取运河名额，不主动改变客户之间的服务顺序；所有积压货物按同一节奏滚动到后续航次。", "Continue pursuing canal slots in proportion to each customer's existing volume without changing service order; roll all backlog into later sailings at the same cadence.", "规则透明且容易解释，但库存只剩数天的客户也可能与可等待货物一起延误。", "The rule is transparent and easy to explain, but customers with only days of inventory may be delayed alongside cargo that can wait."),
          option("B", "关键货物优先，其余改道或延期", "Prioritize critical cargo; reroute or defer the rest", "把有限名额优先分给可能停线或违约的货物；对库存较充足的货物比较绕行与延期成本，并提交具名负责人批准。", "Assign scarce slots first to cargo facing production stoppage or contractual failure; compare rerouting and deferral costs for cargo with more inventory and submit the allocation for accountable approval.", "降低最严重的业务损失，但会打破客户之间的比例公平，并把额外成本集中到部分货物。", "Reduces the most severe business loss, but breaks proportional fairness across customers and concentrates extra cost on selected cargo."),
        ],
      },
    ],
  },
  {
    id: "red-sea-security",
    title: l("红海安全风险与商船绕行", "Red Sea security risk and commercial-shipping rerouting"),
    shortTitle: l("红海安全", "Red Sea security"),
    role: l("欧亚海运网络经理", "Europe–Asia ocean network manager"),
    mode: "OCEAN",
    disruption: l("海上安全事件与绕行", "Maritime security disruption and rerouting"),
    region: l("中东", "Middle East"),
    decisionLens: l("安全阈值与停航治理", "Safety thresholds and route governance"),
    stages: [
      {
        moment: "T0",
        date: l("2023 年 12 月 19 日 · 00:00 UTC", "19 December 2023 · 00:00 UTC"),
        status: l("尚未收到新的官方安全通报", "No new official security statement received"),
        context: l("你负责一批计划经红海与苏伊士运河前往欧洲的高优先级货物。市场已经出现安全担忧，但在这个时点，你还没有可用的新官方通报或大规模绕行确认。", "You manage high-priority cargo planned to reach Europe through the Red Sea and Suez Canal. Security concerns are circulating, but at this time you have no new official statement or confirmed large-scale rerouting information."),
        newEvidence: [l("尚无新的官方安全事件通报可供本次决策使用。", "No new official security statement is available for this decision."), l("未确认主要承运商已大规模改变航线。", "No large-scale route change by major carriers is yet confirmed.")],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("经红海与苏伊士运河", "Via the Red Sea and Suez Canal") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 12 天", "About 12 days") },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("备选运输", "Backup transport"), value: l("可绕行好望角；舱位和成本尚未确认", "Cape routing is possible; capacity and cost unconfirmed"), tone: "positive" },
        ],
        question: l("还没有新的官方安全通报，你现在会不会暂停新的红海订舱？", "With no new official security statement, would you suspend new Red Sea bookings now?"),
        options: sameMonitor("维持已批准航线，监测安全阈值", "Keep the approved route and monitor the safety threshold", "暂不触发停航规则。持续跟踪官方安全通报、承运商政策和保险条件；只有在攻击或大规模绕行得到可靠确认后，才升级到安全负责人。", "Do not trigger the route-suspension rule yet. Track official security statements, carrier policy and insurance conditions; escalate to the safety owner only after reliable confirmation of attacks or widespread rerouting.", "避免在证据不足时越过治理流程，但事件快速升级时，留给安全决策的时间会更少。", "Avoids overriding governance on weak evidence, but leaves less time for a safety decision if events escalate quickly."),
      },
      {
        moment: "T1",
        date: l("2023 年 12 月 20 日 · 00:00 UTC", "20 December 2023 · 00:00 UTC"),
        status: l("攻击与承运商绕行已确认", "Attacks and carrier rerouting confirmed"),
        context: l("国际海事组织谴责了针对国际航运的攻击，并报告多家全球运营商正在因威胁改变商船航线。你的货物仍按红海路线计划，但市场运力已开始重新分配。", "The IMO has condemned attacks on international shipping and reports that several global operators are rerouting. Your cargo is still planned through the Red Sea, while market capacity is beginning to shift."),
        newEvidence: [l("针对国际航运的攻击已得到官方确认。", "Attacks against international shipping are officially confirmed."), l("多家全球运营商正在改道。", "Several global operators are rerouting.")],
        operationalFacts: [
          { label: l("原计划路线", "Original route"), value: l("经红海；安全风险已确认", "Via the Red Sea; security risk confirmed"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 11 天", "About 11 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("市场变化", "Market change"), value: l("承运商开始绕行，舱位正在重新分配", "Carriers rerouting; capacity being reallocated") },
          { label: l("备选运输", "Backup transport"), value: l("可绕行好望角；将增加时间和成本", "Cape routing is possible; adds time and cost"), tone: "positive" },
        ],
        question: l("攻击已经确认：公司应统一暂停红海路线，还是继续由各承运商自行决定？", "Attacks are confirmed. Should the company suspend the Red Sea route consistently or continue leaving the decision to each carrier?"),
        options: [
          option("A", "触发公司级红海停航规则", "Trigger a company-wide Red Sea suspension", "把已确认攻击视为统一安全阈值：暂停新的红海路线批准，将受影响货物转入好望角评估队列，并由具名安全负责人批准任何例外。", "Treat the confirmed attacks as a common safety threshold: suspend new Red Sea approvals, move affected cargo into the Cape assessment queue, and require a named safety owner to approve any exception.", "给所有团队一致的安全边界，但会在舱位和成本尚未完全核实时立即扩大绕行需求。", "Creates one consistent safety boundary, but expands Cape demand before capacity and cost are fully validated."),
          option("B", "继续采用承运商逐票判断", "Continue carrier-by-carrier decisions", "不设置公司级停航线。由每家承运商根据自身安全政策决定是否继续红海航行，运营团队每日汇总路线、保险和库存变化。", "Do not impose a company-wide suspension. Let each carrier decide under its own safety policy while operations consolidates daily routing, insurance and inventory changes.", "保留更多舱位和路线灵活性，但相似货物可能得到不一致的安全处理，责任边界也更分散。", "Preserves more capacity and routing flexibility, but similar cargo may receive inconsistent safety treatment and accountability becomes fragmented."),
        ],
      },
      {
        moment: "T2",
        date: l("2024 年 1 月 5 日 · 00:00 UTC", "5 January 2024 · 00:00 UTC"),
        status: l("大规模绕行的时效影响已明确", "Scale and delay impact of rerouting confirmed"),
        context: l("国际海事组织报告至少 18 家航运公司已选择绕行南非，航程平均增加约 10 天，贸易和运价均受到影响。你的库存缓冲已下降到 7 天。", "The IMO reports at least 18 shipping companies routing around South Africa, adding about 10 days and affecting trade and freight rates. Your inventory buffer has fallen to seven days."),
        newEvidence: [l("至少 18 家航运公司已绕行南非。", "At least 18 shipping companies are routing around South Africa."), l("绕行平均会增加约 10 天航程。", "The reroute adds about 10 days to voyages."), l("运价和市场运力已受到影响。", "Freight rates and market capacity are affected.")],
        operationalFacts: [
          { label: l("原计划路线", "Original route"), value: l("经红海；风险仍在持续", "Via the Red Sea; risk remains active"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 7 天", "About 7 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("绕行影响", "Reroute impact"), value: l("约增加 10 天，运价上升", "About 10 extra days; rates rising") },
          { label: l("备选运输", "Backup transport"), value: l("绕行已成为市场常用方案；舱位仍需确认", "Cape routing is now common; capacity still needs confirmation"), tone: "positive" },
        ],
        question: l("行业已大规模绕行，公司应继续统一 no-go，还是允许少数承运商申请红海例外？", "With widespread industry rerouting, should the company keep a common no-go rule or allow selected carriers to request Red Sea exceptions?"),
        options: [
          option("A", "维持统一 no-go，仅安全负责人可例外", "Keep the common no-go rule with safety-owner exceptions only", "继续把红海路线默认设为不可用，按好望角舱位和库存紧迫度安排货物；只有具名安全负责人基于新的风险证据才能批准例外。", "Keep the Red Sea route unavailable by default, sequence cargo by Cape capacity and inventory urgency, and allow exceptions only when a named safety owner has new risk evidence.", "安全和责任边界清楚，但所有货物都要承受约 10 天额外航程及更高运价。", "Safety and accountability are clear, but all cargo absorbs about ten extra days and higher rates."),
          option("B", "开放承运商例外申请", "Open a carrier-exception process", "允许仍愿意航行且满足保险条件的承运商逐票申请红海路线，运营、保险与安全负责人共同审查，不自动恢复整条路线。", "Allow carriers still willing to sail and meeting insurance conditions to request Red Sea routing shipment by shipment, jointly reviewed by operations, insurance and safety owners without reopening the route by default.", "可能保护部分交期和成本，但会重新引入人员安全暴露，并增加逐票治理负担。", "May protect selected delivery dates and cost, but reintroduces safety exposure and adds shipment-by-shipment governance burden."),
        ],
      },
    ],
  },
  {
    id: "faa-notam-outage",
    title: l("2023 年 1 月美国 NOTAM 故障期间的航空货运中断", "U.S. air-cargo disruption during the January 2023 NOTAM outage"),
    shortTitle: l("FAA NOTAM 故障", "FAA NOTAM outage"),
    role: l("美国航空货运运营经理", "U.S. air-cargo operations manager"),
    mode: "AIR",
    disruption: l("航空信息系统故障与全国停飞", "Aviation information outage and nationwide ground stop"),
    region: l("北美", "North America"),
    decisionLens: l("全网事故中的恢复排序", "Recovery sequencing during a network incident"),
    stages: [
      {
        moment: "T0",
        date: l("2023 年 1 月 11 日 · 00:46 UTC", "11 January 2023 · 00:46 UTC"),
        status: l("尚未收到系统故障通报", "No system-outage advisory received"),
        context: l("你负责一批当日在美国转运的高优先级航空货物。现在距离夜间班次截单很近，但在这个时点，你还没有收到 FAA 系统故障或航班受限通报。", "You manage high-priority air cargo moving through the United States that day. The overnight cut-off is approaching, but at this time you have received no FAA system-outage or flight-restriction advisory."),
        newEvidence: [l("尚无 FAA 系统故障通报。", "No FAA system-outage advisory is available."), l("尚无停飞或航班受限信息。", "No ground stop or flight restriction is reported.")],
        operationalFacts: [
          { label: l("计划运输", "Planned movement"), value: l("当日美国境内航空转运", "U.S. domestic air transfer that day") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 5 天", "About 5 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高；航班延误会影响承诺时间", "High; flight delay affects delivery commitment"), tone: "warning" },
          { label: l("恢复队列", "Recovery queue"), value: l("尚未启动；货物按正常截单顺序", "Not activated; cargo follows normal cut-off order") },
        ],
        question: l("在还没有收到 FAA 故障或停飞通知前，你会不会提前调整今天这批航空货物的交运顺序？", "Before any FAA outage or ground-stop notice, would you change the tendering order for today's air cargo?"),
        options: sameMonitor("按正常截单顺序交运", "Tender cargo in normal cut-off order", "维持当日航班和正常货物交运顺序。跟踪 FAA 与承运商通报；只有出现系统故障或航班限制后才启动事故队列。", "Keep the day's flights and normal cargo tendering order. Track FAA and carrier notices, and activate an incident queue only after a system outage or flight restriction appears.", "避免正常运行时人为打乱货站作业，但突发全网中断时需要临时建立恢复优先级。", "Avoids disrupting terminal work during normal operations, but a sudden network outage would require a recovery priority to be built under pressure."),
      },
      {
        moment: "T1",
        date: l("2023 年 1 月 11 日 · 01:21 UTC", "11 January 2023 · 01:21 UTC"),
        status: l("NOTAM 系统故障，但尚未停飞", "NOTAM system failed; no ground stop yet"),
        context: l("FAA 指挥中心已启动运营热线，并报告美国 NOTAM 系统故障，新通告无法处理，暂无恢复时间。此时尚未发布全国停飞。", "The FAA command center has activated an operations hotline and reports that the U.S. NOTAM system has failed, new notices are not being processed, and no restoration estimate is available. No nationwide ground stop has yet been issued."),
        newEvidence: [l("FAA 已启动故障运营热线。", "The FAA has activated an outage operations hotline."), l("NOTAM 系统无法处理新通告。", "The NOTAM system cannot process new notices."), l("暂无恢复时间，但还没有全国停飞。", "There is no restoration estimate, but no nationwide ground stop yet.")],
        operationalFacts: [
          { label: l("当前航班", "Current flight plan"), value: l("尚未官方取消或停飞", "Not officially cancelled or grounded") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 5 天", "About 5 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("恢复预期", "Recovery outlook"), value: l("未知", "Unknown") },
          { label: l("货物位置", "Cargo position"), value: l("可留在始发仓，也可继续交给承运商", "Can remain at origin or continue into carrier custody") },
        ],
        question: l("系统已经故障但还没有发布停飞令，你现在会改变货物的交运顺序吗？", "The system has failed but no ground stop has been issued. Would you change cargo tendering order now?"),
        options: sameMonitor("维持原交运顺序，高频跟踪", "Keep the tendering order and monitor closely", "继续按原订舱和截单顺序交运，不提前调仓或改签。高频跟踪 FAA 与承运商状态；只有航班受到限制后才启动恢复排序。", "Continue tendering against the original bookings and cut-off order without early repositioning or rebooking. Monitor FAA and carrier status closely and start recovery sequencing only after flights are restricted.", "保留仍可运行的航班和现有舱位，但如果升级为全网停飞，恢复队列需要在压力下临时建立。", "Preserves operating flights and booked capacity, but a network-wide stop would force the recovery queue to be built under pressure."),
      },
      {
        moment: "T2",
        date: l("2023 年 1 月 11 日 · 12:22 UTC", "11 January 2023 · 12:22 UTC"),
        status: l("全国停飞已发布", "Nationwide ground stop issued"),
        context: l("由于 NOTAM 系统故障，FAA 已发布覆盖美国所有航班与目的地的全国停飞令，军用和医疗后送航班除外。你的当日航空转运已无法按原计划执行。", "Because the NOTAM system is down, the FAA has issued a nationwide ground stop covering all flights and destinations except military and medical evacuation. Your same-day air transfer can no longer proceed as planned."),
        newEvidence: [l("FAA 已发布全国停飞。", "The FAA has issued a nationwide ground stop."), l("除军用和医疗后送外，所有航班和目的地都受影响。", "All flights and destinations are affected except military and medical evacuation.")],
        operationalFacts: [
          { label: l("原计划", "Original plan"), value: l("当日航空转运；已无法执行", "Same-day air transfer; cannot proceed"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 4 天", "About 4 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("恢复预期", "Recovery outlook"), value: l("停飞已生效；恢复时间未知", "Ground stop active; recovery time unknown") },
          { label: l("恢复能力", "Recovery capacity"), value: l("恢复后的首批舱位有限，顺序尚未确定", "First-wave capacity after recovery will be limited; sequence not set"), tone: "warning" },
        ],
        question: l("全国停飞后，恢复舱位应该由你统一按业务影响排序，还是沿用各承运商原有订舱顺序？", "After the nationwide stop, should recovery capacity be centrally sequenced by business impact or follow each carrier's original booking order?"),
        options: [
          option("A", "建立一个跨承运商恢复序列", "Create one cross-carrier recovery sequence", "盘点所有货物位置和客户影响，按医疗需求、停线风险、库存天数与原承诺统一排序；停飞解除后，把首批可用舱位分给最高影响货物，任何越级由具名负责人批准。", "Inventory cargo location and customer impact across carriers, rank it by medical need, production-stop risk, inventory days and original commitment, and assign first-wave capacity accordingly with named approval for overrides.", "把有限恢复能力用于最严重影响，但会打破原订舱顺序，并需要跨承运商协调和客户解释。", "Uses scarce recovery capacity against the greatest impact, but overrides original booking order and requires cross-carrier coordination and customer explanation."),
          option("B", "沿用各承运商原订舱顺序", "Keep each carrier's original booking order", "不建立统一优先队列。保留各承运商当前订舱和货物状态，停飞解除后由承运商按自身网络规则恢复。", "Do not create a central priority queue. Preserve each carrier's current bookings and cargo status and let carriers recover freight under their own network rules after the stop is lifted.", "执行简单且尊重既有订舱，但关键货物可能排在低影响货物之后，整体恢复也缺少统一视图。", "Is simpler and respects existing bookings, but critical cargo may sit behind lower-impact freight and recovery lacks one network-wide view."),
        ],
      },
    ],
  },
  {
    id: "cyclone-gabrielle-roads",
    title: l("加布里埃尔气旋期间的新西兰公路网中断", "New Zealand road-network disruption during Cyclone Gabrielle"),
    shortTitle: l("加布里埃尔气旋", "Cyclone Gabrielle"),
    role: l("新西兰北岛公路运输经理", "New Zealand North Island road-freight manager"),
    mode: "ROAD",
    disruption: l("极端天气与公路网中断", "Extreme weather and road-network disruption"),
    region: l("大洋洲", "Oceania"),
    decisionLens: l("没有安全路线时的 no-go 边界", "The no-go boundary when no safe route exists"),
    stages: [
      {
        moment: "T0",
        date: l("2023 年 2 月 13 日 · 10:38 NZDT", "13 February 2023 · 10:38 NZDT"),
        status: l("尚未收到目标公路关闭通知", "No target-road closure notice received"),
        context: l("你负责一批在新西兰北岛跨区运输的高优先级公路货物。气旋带来强风降雨，但在这个分钟，你还没有收到关于目标国道关闭的交通管理通知。", "You manage high-priority road freight moving across New Zealand's North Island. The cyclone is bringing wind and rain, but at this minute you have no transport-agency notice that the target state highways are closed."),
        newEvidence: [l("尚无目标国道的关闭通知。", "No target state-highway closure notice is available."), l("尚无重型车辆绕行限制信息。", "No heavy-vehicle detour restriction is reported.")],
        operationalFacts: [
          { label: l("计划路线", "Planned route"), value: l("经北岛国道网络", "Via the North Island state-highway network") },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 6 天", "About 6 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("安全门槛", "Safety threshold"), value: l("按官方关闭、能见度和积水条件触发 no-go", "No-go triggered by official closure, visibility or flooding") },
        ],
        question: l("天气正在恶化但还没有封路通知，你会让车队照常出发，还是先暂停进入风险最高的区域？", "The weather is worsening but no road closure is posted. Would you dispatch as planned or pause entry into the highest-risk area?"),
        options: sameMonitor("按既定安全门槛继续发车", "Continue dispatch under the existing safety threshold", "不因为天气预警单独停运。司机按官方关闭、能见度、积水和现场风险标准执行；任何一项达到阈值即停止进入相关路段。", "Do not stop freight because of the weather warning alone. Drivers follow official closure, visibility, flooding and site-risk criteria and stop entering a corridor as soon as any threshold is met.", "避免在道路仍开放时全面停运，但要求现场信息及时可靠，天气快速恶化时司机决策压力较大。", "Avoids a network-wide stop while roads remain open, but depends on timely field information and places pressure on drivers if conditions deteriorate quickly."),
      },
      {
        moment: "T1",
        date: l("2023 年 2 月 13 日 · 10:40 NZDT", "13 February 2023 · 10:40 NZDT"),
        status: l("科罗曼德尔多条公路已关闭", "Multiple Coromandel highways closed"),
        context: l("交通管理机构报告，气旋的强风和降雨造成倒木、洪水和杂物阻断，25 号国道多处关闭，25A 号国道全线关闭。你的部分货物原计划使用这些路段。", "The transport agency reports that cyclone wind and rain have caused fallen trees, flooding and debris. Parts of State Highway 25 are closed and State Highway 25A is fully closed. Some of your cargo was planned over these roads."),
        newEvidence: [l("25 号国道多处被倒木、洪水和杂物阻断。", "Parts of State Highway 25 are blocked by fallen trees, flooding and debris."), l("25A 号国道已全线关闭。", "State Highway 25A is closed over its full length.")],
        operationalFacts: [
          { label: l("原计划路线", "Original route"), value: l("经 SH25 / SH25A；已受阻", "Via SH25 / SH25A; now disrupted"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 4 天", "About 4 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("现场条件", "Road conditions"), value: l("洪水、倒木与杂物；安全性不确定", "Flooding, fallen trees and debris; safety uncertain") },
          { label: l("安全范围", "Safety scope"), value: l("已确认关闭 SH25 / SH25A；其他区域状态不一", "SH25 / SH25A confirmed closed; other areas vary") },
        ],
        question: l("部分公路关闭后，no-go 应只覆盖已关闭路段，还是扩大到整个受气旋影响区域？", "With some highways closed, should no-go apply only to confirmed closures or expand across the cyclone-affected region?"),
        options: [
          option("A", "封闭路段 no-go，其他路线逐条放行", "No-go on closed roads; release other routes individually", "禁止车辆进入 SH25 与 SH25A；其他线路只有在交通机构确认开放、司机完成现场风险检查且重型车辆条件满足后才逐条放行。", "Prohibit entry to SH25 and SH25A; release other routes individually only after the agency confirms them open, drivers complete a field-risk check and heavy-vehicle conditions are met.", "保留部分区域运输能力，但不同路线状态变化快，调度员和司机需要持续做边界判断。", "Preserves some regional capacity, but rapidly changing route conditions require continuous boundary decisions by dispatchers and drivers."),
          option("B", "整个受影响区域暂时 no-go", "Apply a temporary regional no-go", "暂停气旋影响区域内所有新发车，把车辆和货物留在安全站点；只有交通机构给出稳定路网信息后才逐步恢复。", "Pause all new dispatch into the cyclone-affected region and keep vehicles and cargo at safe depots; resume gradually only after the agency provides a stable network picture.", "安全规则简单一致，但会停止仍可能安全通行的路线，并更快消耗客户库存。", "The safety rule is simple and consistent, but stops routes that may still be passable and consumes customer inventory faster."),
        ],
      },
      {
        moment: "T2",
        date: l("2023 年 2 月 14 日 · 19:45 NZDT", "14 February 2023 · 19:45 NZDT"),
        status: l("北地地区大范围与外界隔离", "Northland largely isolated from the road network"),
        context: l("新的道路更新显示，1 号国道多处滑坡，16 号和 14 号国道洪水，15 号和 12 号国道也有关闭。北地地区大范围与外界隔离，当晚 Brynderwyn 至 Waipu 关闭路段没有重型车辆绕行路线。", "New road updates show multiple slips on State Highway 1, flooding on Highways 16 and 14, and further closures on 15 and 12. Northland is largely isolated, with no heavy-vehicle detour that night around the Brynderwyn–Waipu closure."),
        newEvidence: [l("SH1 多处滑坡，多条其他国道洪水或关闭。", "SH1 has multiple slips and several other highways are flooded or closed."), l("北地地区大范围与外界隔离。", "Northland is largely isolated."), l("当晚没有可用的重型车辆绕行路线。", "No heavy-vehicle detour is available that night.")],
        operationalFacts: [
          { label: l("原计划路线", "Original route"), value: l("多条国道已中断", "Multiple state highways disrupted"), tone: "warning" },
          { label: l("库存缓冲", "Inventory buffer"), value: l("约可支撑 3 天", "About 3 days"), tone: "warning" },
          { label: l("客户优先级", "Customer priority"), value: l("高", "High"), tone: "warning" },
          { label: l("区域可达性", "Regional access"), value: l("北地大范围隔离", "Northland largely isolated") },
          { label: l("重型车辆备选", "Heavy-vehicle alternative"), value: l("当晚不可用", "Unavailable that night"), tone: "warning" },
        ],
        question: l("当晚不存在安全的重型车辆通道：是否坚持绝对 no-go，还是允许满足同等安全标准的分段应急交接？", "No safe heavy-vehicle corridor exists tonight. Should no-go remain absolute or allow a staged emergency handoff that meets the same safety standard?"),
        options: [
          option("A", "坚持绝对 no-go", "Keep the no-go absolute", "暂停所有进入北地的车辆，货物与司机留在安全站点；只有交通机构确认完整的重型车辆通道后恢复，不以库存或客户压力作为例外理由。", "Hold every vehicle entering Northland and keep cargo and drivers at safe depots; resume only after the agency confirms a complete heavy-vehicle corridor, with no exception based on inventory or customer pressure.", "人员安全和责任边界最清楚，但库存只剩 3 天，医疗或停线货物也无法提前移动。", "Creates the clearest safety and accountability boundary, but only three inventory days remain and even medical or line-stop cargo cannot move early."),
          option("B", "允许同等安全标准的分段交接", "Allow a staged handoff under the same safety standard", "仅为医疗或停线货物核实安全站点间的分段交接、小型车辆载重与每段道路状态；每一段都必须独立满足原安全门槛，并由具名负责人批准。", "For medical or production-stop cargo only, validate staged handoffs between safe depots, smaller-vehicle loads and each road segment; every leg must independently meet the original safety threshold and receive named approval.", "可能移动少量关键货物，但协调复杂且容易产生‘应急就是降低标准’的错误压力。", "May move a small amount of critical cargo, but coordination is complex and can create pressure to treat emergency status as permission to lower standards."),
        ],
      },
    ],
  },
];
